### ISSUE TITLE
Numerous deprecation warnings on install

### ISSUE THREAD

**Issue by quinton-ashley** [mozilla/web-ext#1334] opened 2018-06-14 01:16 UTC
```
npm install --global web-ext
npm WARN deprecated js-select@0.6.0: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated markdown-to-ast@3.4.0: See https://github.com/textlint/textlint/issues/455
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
/usr/local/bin/web-ext -> /usr/local/lib/node_modules/web-ext/bin/web-ext

> dtrace-provider@0.8.7 install /usr/local/lib/node_modules/web-ext/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

  ACTION binding_gyp_ndtp_target_build_ndtp .
  TOUCH Release/obj.target/ndtp.stamp

> fsevents@1.2.4 install /usr/local/lib/node_modules/web-ext/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/lib/node_modules/web-ext/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/web-ext/node_modules/spawn-sync
> node postinstall

npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by ExE-Boss** [comment] 2018-06-16 04:28
`js-select` is depended upon by [`@cliqz-oss/firefox-client`](https://github.com/harthur/firefox-client), which is also no longer maintained.

The remaining deprecated dependencies are sub-dependencies of dependencies of [`addons-linter`](https://github.com/mozilla/addons-linter):

<pre>
<a href="https://github.com/mozilla/addons-linter">addons-linter</a> &gt; doctoc &gt; markdown-to-ast@3.4.0
<a href="https://github.com/mozilla/addons-linter">addons-linter</a> &gt; po2json &gt; nomnom@1.8.1 
<a href="https://github.com/mozilla/addons-linter">addons-linter</a> &gt; snyk &gt; proxy-agent &gt; socks-proxy-agent &gt; socks@1.1.10
</pre>

**Comment by EnTeQuAk** [comment] 2018-06-16 12:07
for the linter:

* doctoc has recently been moved to a devDependency, so should be less of a problem
* po2json actually shouldn't be a regular dependency but a dev dependency, I'll create an issue to fix this
* snyk is a devDependency :thinking:

**Comment by ExE-Boss** [comment] 2018-06-16 12:12
@EnTeQuAk `snyk` has been moved to `devDependencies` in https://github.com/mozilla/addons-linter/commit/3ff0a20dd2fcd2b1d063ccd461bf4cf824dbd1bf, which hasn’t yet been published to npm, same with `doctoc` in https://github.com/mozilla/addons-linter/commit/f202fb9f01a7993f85a68ed12f5d616221c43ba6.

**Comment by beyera** [comment] 2020-02-01 01:00
As of version 4, there are still dependencies which have been deprecated. 
 
```
❯ npm i -g web-ext
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated js-select@0.6.0: Package no longer supported. Contact support@npmjs.com for more info.
```

**Comment by Rob--W** [comment] 2020-02-04 18:56
To be independent of any cached packages, I bypassed the cache and got 4 deprecation warnings when installing web-ext 4.0.0:

```
$ npm i --cache=tmpdir/ web-ext
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated js-select@0.6.0: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated jetpack-id@1.0.0: Jetpack extensions are no longer supported by Firefox. Use web-ext instead to build a WebExtension.
```

`core-js` is depended upon via the `@babel/polyfill` package, which itself has been deprecated in favor of including the dependencies directly, per https://babeljs.io/docs/en/next/babel-polyfill.html

`js-select` is depended upon by `@cliqz-oss/firefox-client@0.3.1`

`circular-json` is depended upon by `flat-cache`. The package lock is pinned on 1.3.4, but the latest version is 2.0.1 which doesn't have this issue.

`jetpack-id` is depended upon by `firefox-profile`. To get rid of this dependency, the Jetpack logic could be inlined or [support for Jetpack add-ons](https://github.com/saadtazi/firefox-profile-js/blob/cafc793d940a779d280103ae17d02a92de862efc/lib/firefox_profile.js#L635-L645) could be removed from the library.

**Comment by clemstoquart** [comment] 2020-02-14 09:10
Hi @Rob--W 

I don't know this project very well but can we simply remove the `@babel/polyfill` dependency ? Not sure it's useful anymore since the project requires at least node 10.

**Comment by rpl** [comment] 2021-06-22 12:21
Closing as a duplicate of #2130

**Closed by rpl** 2021-06-22 12:21 UTC
Labels: state: duplicate
