### ISSUE TITLE
Show an error when passing an argument to the lint command

### ISSUE THREAD

**Issue by kumar303** [mozilla/web-ext#398] opened 2016-07-29 16:47 UTC
If you run `web-ext lint ./some-file.xpi` then it will not lint `some-file.xpi`. It ignores command arguments. However, the `addons-linter` accepts arguments so this could be confusing. We should raise an error if an argument is given.

See https://github.com/mozilla/web-ext/issues/396

**Comment by shubheksha** [comment] 2016-08-27 07:12
@rpl, I'd like to work on this! I understand what the issue is. Basically the web-ext linter isn't supposed to accept arguments, but is based on the addons-linter which does accept arguments, so it can get confusing. I went through the source of the linter we are using & I have one question: how is the `sourceDir` param being used [here](https://github.com/mozilla/web-ext/blob/master/src/cmd/lint.js#L75) directly? I mean, how is it this file interacting with yargs to get access to it?

**Comment by rpl** [comment] 2016-08-29 10:23
@shubheksha That's great!

Here is a brief sketch related to how the program arguments are flowing inside web-ext:

- the cli options are initially stored in process.argv, as a simple array of strings
- our application is executed as follows:
  - bin/web-ext ==(calls)=> src/main => src/program main => src/program Program.prototype.run => "src/cmd/<command_name>" (command implementation module)

As we saw in the previous pull request you worked on, the `main` in "src/program" creates an instance of `Program`, defines the `yargs` commands and options on it and then it calls `Program.prototype.run`.

`Program` configures `yargs` to use `process.argv` as the source of the command line arguments by default (but optionally we can pass an explicit `argv` parameter, which is used in the test suite to inject the combinations of arguments that we want to test).

All the commands are implemented by their own "src/cmd/<command_name>" module, and they are all collected in ["src/cmd/index"](https://github.com/mozilla/web-ext/blob/master/src/cmd/index.js), and their module names correspond to their related yargs command (e.g. the yargs command "build" will execute "cmd/build", the command "lint" will execute "cmd/lint" etc).

So, in our scenario, 'src/cmd/lint" is still a module of "web-ext", it receives the cli arguments parsed by our yargs config, and then it creates a Linter instance using the code exported by the "addons-linter" and it passes to it the needed options (as the addons-linter expect to receive them).

In particular, the "addons-linter" expects to get the path to the addon (or to the xpi file) to lint as its argv rest (a command line argument which is not a yargs command or a yargs option), which is `_` in `yargs` conventions (http://yargs.js.org/docs/#examples-and-non-hyphenated-options-too-just-use-argv_), and so we basically put the `sourceDir` parsed by our yargs config into the `_` array that we pass to the `createLinter` function (https://github.com/mozilla/web-ext/blob/master/src/cmd/lint.js#L75).

To fix this we need to look at "src/program" and plan the needed changes to ensure that, after yargs has parsed process.argv, looking for the commands and options we defined, there shouldn't be anything left in the `_` array property contained into its results.

**Comment by shubheksha** [comment] 2016-09-02 17:51
Sorry for the delay in replying! Once again, thank you for such a clear and detailed explanation. :smile: 
I understood everything you said, however I am kinda confused about the last line -- if we remove the everything from the `_` array property, how will we get the the directory to lint? Isn't that being assigned to the `sourceDir` here to accomplish that? Or do we need to mimic that behavior without using the `_` array property?

**Comment by kumar303** [comment] 2016-09-02 19:56
It may be possible to just use [demand()](http://yargs.js.org/docs/#methods-demandcount-max-msg) to say that `lint` and all other sub-commands do not take arguments. Here is a quick test:
````diff
diff --git a/src/program.js b/src/program.js
index e67ea2a..eedaaeb 100644
--- a/src/program.js
+++ b/src/program.js
@@ -38,6 +38,7 @@ export class Program {
         return;
       }
       return yargs
+        .demand(0, 0, 'This command does not take any arguments')
         .strict()
         .exitProcess(this.shouldExitProgram)
         // Calling env() will be unnecessary after

````

**Closed** 2016-09-08 19:49 UTC
