### ISSUE TITLE
Exclude web-ext-artifacts folder from `web-ext build`

### ISSUE THREAD

**Issue by callahad** [mozilla/web-ext#291] opened 2016-06-15 14:12 UTC
When running:

    web-ext build

The `web-ext-artifacts` directory can be completely ignored. Currently it is not ignored. You can see it included by checking the listing inside the `.zip`. Here is an example using [beatify](https://github.com/mdn/webextensions-examples/tree/master/beastify).
````
$ unzip -l web-ext-artifacts/beastify-1.0.zip
Archive:  web-ext-artifacts/beastify-1.0.zip
  Length     Date   Time    Name
 --------    ----   ----    ----
        0  09-21-16 18:01   beasts/
        0  09-21-16 18:01   content_scripts/
        0  09-21-16 18:01   icons/
        0  09-21-16 18:01   popup/
        0  09-21-16 18:01   web-ext-artifacts/
        ...
````

**Comment by kumar303** [comment] 2016-06-20 17:17
I'm not sure if we have an issue for it but there is a patch in the works: https://github.com/mozilla/web-ext/pull/275

**Comment by kumar303** [comment] 2016-09-21 23:00
The contributor working on #275 told me he doesn't currently have time to complete the work so this bug is available for anyone else.

**Comment by kumar303** [comment] 2016-09-21 23:06
Actually, this isn't such a good first bug because it involves making some architectural changes to [FileFilter](https://github.com/mozilla/web-ext/blob/master/src/cmd/build.js#L133).

This isn't very high priority though because the problematic files *inside* `web-ext-artifacts` (such as other XPI files) are already ignored.

**Comment by kumar303** [comment] 2016-10-20 19:02
oops, this was a dupe of https://github.com/mozilla/web-ext/issues/186

**Closed by kumar303** 2016-10-20 19:02 UTC
Labels: bug
