### ISSUE TITLE
Error: Signing took too long to complete.

### ISSUE THREAD

**Issue by sshahcodes** [mozilla/web-ext#1857] opened 2020-03-08 05:51 UTC
### Is this a feature request or a bug?
Bug. There is similer issues(now closed)  https://github.com/mozilla/web-ext/issues/1773  but trying out solutions mentioned there did not work.

### What is the current behavior?
```
Validating add-on [................................................................................................................................................................................]
Validation results: https://addons.mozilla.org/en-US/developers/upload/1bdcaae87f9144a58f721c7561f548c7
Signing add-on [...................................................................................................................................................................................]

Error: Signing took too long to complete; last status: {"guid":"{97eeef94-56df-45cf-a7f1-76106bbd5ff9}","active":false,"automated_signing":true,"url":"https://addons.mozilla.org/api/v3/addons/%7B97eeef94-56df-45cf-a7f1-76106bbd5ff9%7D/versions/1.0.22/uploads/1bdcaae87f9144a58f721c7561f548c7/","files":[{"download_url":"https://addons.mozilla.org/api/v3/file/3522109/trasa-1.0.22-an+fx.xpi?src=api","hash":"sha256:f2ebc959531a325d793517f444fbbb1868e0081d1e44a93288efb43f56856163","signed":false}],"passed_review":false,"pk":"1bdcaae87f9144a58f721c7561f548...
    at Timeout.r [as _onTimeout] (/usr/lib/node_modules/web-ext/node_modules/sign-addon/dist/webpack:/src/amo-client.js:312:11)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

```

### What is the expected or desired behavior?
Signed extension. I am facing this issue suddenly.

```
$ node --version && npm --version && web-ext --version
v12.16.1
6.13.4
4.1.0
```

**Comment by Rob--W** [comment] 2020-03-08 18:30
Is this issue consistently reproducible? What are you trying to sign?

**Comment by nzambello** [comment] 2020-03-08 19:39
It's occuring to me, too.

**Comment by sagibrant** [comment] 2020-03-09 08:35
It's also occuring to me. I checked the signed addon versions and find that the addon is uploaded and signed. The issue is that we cannot find the signed addon file locally. I guess it is related to the download.

**Comment by diox** [comment] 2020-03-09 10:36
This was probably caused by https://github.com/mozilla/addons-server/issues/13675 which has been resolved.

**Comment by Rob--W** [comment] 2020-03-09 11:26
Closing this issue since the AMO-side issue has allegedly been resolved.

Please comment if you are still experiencing this issue.
(If you are reading this comment in the future, please open a new issue instead of commenting here, since that issue is probably unrelated to this one)

**Closed by Rob--W** 2020-03-09 11:26 UTC

**Comment by EvHaus** [comment] 2020-04-22 22:12
My team and I have been having this issue for the past 3 days. We're unable to sign any of our addons due to this message:

```
Error: Signing took too long to complete; last status: {"guid":"hidden","active":false,"automated_signing":true,"url":"https://addons.mozilla.org/api/v3/addons/hidden/","files":[],"passed_review":false,"pk":"hidden","processed":true,"reviewed":false,"valid":true,"validation_results":{"errors":0,"warnings":63,"notices":0,"success":true,"compatibility_summary":{"warnings":0,"errors":0,"notices":0},"metadata":{"listed":false,"identif...
    at Timeout.r [as _onTimeout] (/hidden/node_modules/sign-addon/dist/webpack:/src/amo-client.js:312:11)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

Using `web-ext@4.1.0`. It's been happening consistently for the past 3 days but worked fine before then.

**Comment by mtatarau90** [comment] 2021-09-06 12:30
Any news about this issue?

I have the same issue, but is very strange because everything works fine till few months ago. 
My environment: 
` node --version && npm --version && web-ext --version
v16.4.2
7.18.1
6.3.0
`
