### ISSUE TITLE
Attaching web-ext to a running Firefox instance

### ISSUE THREAD

**Issue by mYnDstrEAm** [mozilla/web-ext#2115] opened 2021-01-09 00:15 UTC
### What is the current behavior?

When I run `web-ext run --verbose` I get:

```
Firefox args: -start-debugger-server port -foreground -no-remote -profile /tmp/id
...
Connecting to Firefox on port port
Retrying Firefox (0); connection error: Error: connect ECONNREFUSED 127.0.0.1:port
...
installTemporaryAddon: Error: Error: Could not install add-on at '/home/username/folder': Error: Extension is invalid
```

I think this is because I sandboxed my Firefox with firejail. Instead of opening a new instance of Firefox I'd like to either specify a few things of the instance to start (or at least the profile directory, not sure if anything else is needed) or attach web-ext to a running Firefox instance (like one started like this: `firejail --noblacklist=/tmp/ firefox -no-remote -profile ~/directory/firefoxprofile`).

I  can spawn an instance of Firefox with the above command but not with `web-ext run --verbose --firefox="firejail ..."  -profile ~/dir/firefoxprofile`: it says `[debug] Running Firefox with profile at /tmp/id Error: spawn firejail --noblacklist=/home/username/.web-ext-config.js --noblacklist=/dir/ firefox -no-remote ENOENT   at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)` or with: 
 `web-ext --no-config-discovery run --verbose --firefox="firejail  --noblacklist=/dir/ firefox -no-remote" --firefox-profile="~/dir/firefoxprofile"`: `Could not copy Firefox profile from ~/dir/firefoxprofile: Error: cannot find profile ~/dir/firefoxprofile` even though that folder exists, has the files in it and can be used to spawn a Firefox instance the usual way (running the command of --firefox=). (Btw it would be nice if one could specify another folder than /tmp.) Setting `--profile-create-if-missing` didn't help with the ENOENT problem. Maybe #521 is related.

### What is the expected or desired behavior?
web-ext run prompting the user to either specify a running Firefox instance and/or allowing to configure the instance to be started

### Version information (for bug reports)

* **Firefox version**:
* **Your OS and version**:
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
v15.5.1 (doesn't work with older node versions either)
6.14.10
5.4.1

**Comment by rpl** [comment] 2021-01-11 17:46
@mYnDstrEAm I think that you may be able to get around that issue with the command line arguments by using both `--firefox` and `--arg`, e.g. something like `web-ext run --firefox /path/to/firejail --arg '--noblacklist=/path/to/tmp/dir` --arg 'firefox', --arg '-no-remote'` or by wrapping the command you want to run into a shell script and pass that as a "Fake Firefox binary path" using `--firefox`.

The enhancement request (connecting to an existing Firefox instance) is a duplicate of an existing one, #521, and so I'm closing this as a duplicate of that (but let me know if the approach described above did workaround your more immediate issue).

**Closed** 2021-01-11 17:47 UTC
Labels: state: duplicate
