### ISSUE TITLE
web-ext sign fails on removed addons

### ISSUE THREAD

**Issue by Smile4ever** [mozilla/web-ext#1325] opened 2018-05-29 16:57 UTC
### Is this a feature request or a bug?
Bug

### What is the current behavior?
1. I used web-ext sign. Works well.
2. Remove the addon on addons.mozilla.org
3. I used web-ext sign. Fails, but web-ext seems to create versions in the background nonetheless. The e-mail I get for downloading the new version is fine, but the link doesn't work because the addon is still in it's "deleted" state.
4. When re-trying the same as step 3, it complains about the version number already existing.

### What is the expected or desired behavior?
Undelete the addon when publishing a new version using web-ext sign.

### Version information (for bug reports)

node --version && npm --version && web-ext --version
v10.0.0
6.0.0
2.6.0

### Attachments
[bug-clipboardRead.zip](https://github.com/mozilla/web-ext/files/2049482/bug-clipboardRead.zip)
[LOG.txt](https://github.com/mozilla/web-ext/files/2049483/LOG.txt)

**Comment by Rob--W** [comment] 2018-10-25 13:44
Looks like a duplicate of #1111 .

**Closed by Rob--W** 2018-10-25 13:44 UTC
