### ISSUE TITLE
npm script for chrome doesn't works with npm v@7.7.0 or later

### ISSUE THREAD

**Issue by ZiaUrR3hman** [mozilla/web-ext#2216] opened 2021-04-07 09:01 UTC
### Is this a feature request or a bug?
Bug

### What is the current behavior?

`package.json`
```json
"scripts": {
 "chrome": "web-ext run --target=chromium  --source-dir ./dist/ --start-url https://www.github.com --chromium-profile='C:\\Users\\zia\\AppData\\Local\\Google\\Chrome\\User Data\\' --arg='--profile-directory=Profile 1' --keep-profile-changes",
}
```    

### What is the expected or desired behavior?
Expect chrome instance gets lunched 

### Version information (for bug reports)

* **Firefox version**: works fine on firefox
* **Chrome version**:  Version 89.0.4389.114 (Official Build) (64-bit)
* **Your OS and version**: 
  * Edition	Windows 10 Home
  * Version	20H2

````
node v15.12.0
npm v7.8.0
 (works fine with v7.6.3 or below)
web-ext v6.0.0
````

###Logs
[2021-04-07T08_28_52_239Z-debug.log](https://github.com/mozilla/web-ext/files/6270354/2021-04-07T08_28_52_239Z-debug.log)

**Comment by rpl** [comment] 2021-04-13 13:39
@ZiaUrR3hman does it work if you execute the command at the end of the attached log?
```
C:\Windows\system32\cmd.exe /d /s /c web-ext run --target=chromium --chromium-profile='C:\Users\zia\AppData\Local\Google\Chrome\User Data\' args='--profile-directory Profile 1' --source-dir=./dist/ --start-url https://www.github.com  --keep-profile-changes
```

If it doesn't run chrome neither, it may be useful to know what errors is being logged (if any) when that command is executed manually.

Given that the issue explicitly mention that the issue is being triggered on npm v7.7.0 or later, does the same npm script work fine in npm v6? have you tried to bisect on which npm version >= 6 the issue did start to happen?

(as a side note it seems that `args` is missing the `--` in the logs but not in the scripts.run value, which seems odd, is the logs from that same npm script or it may have been collected from one that was missing the `--` for the `args` option?,  I'm not sure that it can trigger the issue you are experiencing, but it may be worth checking that too).

**Comment by rpl** [comment] 2021-04-13 20:07
@ZiaUrR3hman eh, apparently the issue is due to something npm changes in the way they handle the quote in the npm scripts, and that is making the resulting web-ext command to be wrong because of the space in the --chromium-profile option value, which makes the process.argv array received by web-ext to look like the following:

```
[
  'run',
  '--target=chromium',
  ...
  '--chromium-profile='C:\\Users\\username\\AppData\\Local\\Google\\Chrome\\User',
  'Data'
]
```

and that triggers the `This command does not take any arguments` error due to the last unexpected 'Data' argument.

I don't use Windows as my main system but based on a quick search it seems that to properly quote a string in windows you have to use the double-quotes. I tried that and the following seems to work for me:

```
 "chrome": "web-ext run --target=chromium  --source-dir ./dist/ --start-url https://www.github.com --chromium-profile=\"C:\\Users\\zia\\AppData\\Local\\Google\\Chrome\\User Data\" --arg=\"--profile-directory=Profile 1\" --keep-profile-changes"
```

(I haven't tried but I think that another option may be to use environment variables for those options, if I recall correctly yargs conventions they should be `WEB_EXT_CHROMIUM_PROFILE` and `WEB_EXT_ARG`).

I'm going to closing this issue as invalid because technically this is more likely a change in npm paired with the wrong way to quote strings in windows (which funnily enough it is the opposite of the way I would usually quote a string in *nix, where I would default to the single quote)

**Closed** 2021-04-13 20:07 UTC
Labels: state: invalid
