### ISSUE TITLE
Can't start Firefox with extension: "Temporary add-on installation is not supported in this version of Firefox"

### ISSUE THREAD

**Issue by fo-fo** [mozilla/web-ext#1937] opened 2020-06-22 19:43 UTC
### Is this a feature request or a bug?

Bug.

### What is the current behavior?

web-ext fails to start Firefox.

Command:
`web-ext --source-dir dist run --verbose --firefox-profile extension-dev --keep-profile-changes --start-url www.google.com`

Verbose log:
```
[firefox/index.js][debug] Running Firefox with profile at /Users/xxx/Library/Application Support/Firefox/Profiles/gkgwv2q7.extension-dev
[firefox/index.js][debug] Executing Firefox binary: /Applications/Firefox.app/Contents/MacOS/firefox-bin
[firefox/index.js][debug] Firefox args: -start-debugger-server 59412 -foreground -no-remote -profile /Users/xxx/Library/Application Support/Firefox/Profiles/gkgwv2q7.extension-dev --url www.google.com
[firefox/index.js][info] Use --verbose or open Tools > Web Developer > Browser Console to see logging
[firefox/remote.js][debug] Connecting to the remote Firefox debugger
[firefox/remote.js][debug] Connecting to Firefox on port 59412
[firefox/remote.js][debug] Retrying Firefox (0); connection error: Error: connect ECONNREFUSED 127.0.0.1:59412
[firefox/remote.js][debug] Connecting to Firefox on port 59412
[firefox/remote.js][debug] Retrying Firefox (1); connection error: Error: connect ECONNREFUSED 127.0.0.1:59412
[firefox/remote.js][debug] Connecting to Firefox on port 59412
[firefox/remote.js][debug] Retrying Firefox (2); connection error: Error: connect ECONNREFUSED 127.0.0.1:59412
[firefox/remote.js][debug] Connecting to Firefox on port 59412
[firefox/remote.js][debug] Retrying Firefox (3); connection error: Error: connect ECONNREFUSED 127.0.0.1:59412
[firefox/remote.js][debug] Connecting to Firefox on port 59412
[firefox/remote.js][debug] Retrying Firefox (4); connection error: Error: connect ECONNREFUSED 127.0.0.1:59412
[firefox/remote.js][debug] Connecting to Firefox on port 59412
[firefox/index.js][debug] Firefox stdout: Started devtools server on 59412
[firefox/remote.js][debug] Retrying Firefox (5); connection error: Error: connect ECONNREFUSED 127.0.0.1:59412
[firefox/remote.js][debug] Connecting to Firefox on port 59412
[firefox/remote.js][debug] Connected to the remote Firefox debugger on port 59412
[firefox/remote.js][debug] listTabs returned a falsey addonsActor: undefined
[extension-runners/firefox-desktop.js][debug] Caught: c: This is an older version of Firefox that does not provide an add-ons actor for remote installation. Try Firefox 49 or higher.
[program.js][error] 
o: Temporary add-on installation is not supported in this version of Firefox (you need Firefox 49 or higher). For older Firefox versions, use --pre-install
    at c.startFirefoxInstance (/Users/xxx/Documents/personal/dev/myproject/server/node_modules/web-ext/dist/web-ext.js:1:51601)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

### What is the expected or desired behavior?

Firefox should start because 77 > 49.

### Version information (for bug reports)

* **Firefox version**: Firefox 77.0.1 (64-bit)
* **Your OS and version**: macOS Catalina 10.15.5
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````

node version: v13.12.0
yarn version: 1.22.4
web-ext version: 4.1.0

**Comment by Rob--W** [comment] 2020-06-22 20:24
You should update `web-ext` to 4.2.0 or higher. The current latest version is 4.3.0.

Duplicate of #1932, #1921, #1884, fixed by #1886

**Closed by Rob--W** 2020-06-22 20:24 UTC
