### ISSUE TITLE
NS_ERROR_FILE_ACCESS_DENIED when attempting to install temporary add-on on Android 11

### ISSUE THREAD

**Issue by palant** [mozilla/web-ext#2207] opened 2021-03-18 13:48 UTC
### Is this a feature request or a bug?

Bug

### What is the current behavior?

Running `web-ext run --target=firefox-android --android-device=id --firefox-apk=org.mozilla.fenix` results in the following error:

> o: installTemporaryAddon: Error: Error: Could not install add-on at '/sdcard/web-ext-artifacts-1616072466257/webextensions_test-1.0.xpi': [Exception... "Component returned failure code: 0x80520015 (NS_ERROR_FILE_ACCESS_DENIED) [nsIZipReader.open]"  nsresult: "0x80520015 (NS_ERROR_FILE_ACCESS_DENIED)"  location: "JS frame :: resource://gre/modules/addons/XPIInstall.jsm :: XPIPackage :: line 321"  data: no]
>     at b.installTemporaryAddon (node_modules/web-ext/dist/web-ext.js:1:43043)
>     at processTicksAndRejections (node:internal/process/task_queues:94:5)
>     at w.rdpInstallExtensions (node_modules/web-ext/dist/web-ext.js:1:27002)
>     at w.run (node_modules/web-ext/dist/web-ext.js:1:20597)
>     at async Promise.all (index 0)
>     at x.run (node_modules/web-ext/dist/web-ext.js:1:5299)
>     at $ (node_modules/web-ext/dist/web-ext.js:1:10137)
>     at O.execute (node_modules/web-ext/dist/web-ext.js:1:64433)

This is only an issue when Fenix runs on Android 11, the same works fine on Android 9. I suspect that this is due to scoped storage enforcement: https://developer.android.com/about/versions/11/privacy/storage#scoped-storage

### What is the expected or desired behavior?

The temporary add-on should install successfully.

### Version information (for bug reports)

* **Firefox version**: AC: 74.0, GV: 88.0a1, AS 73.0.1
* **Your OS and version**: Android 11
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
> v15.11.0
> 7.6.0
> 6.0.0

**Comment by Rob--W** [comment] 2021-03-18 14:27
Thanks for your reports.

This is a duplicate of #2173 and fixed by #2200, which has been merged last hour.

**Closed by Rob--W** 2021-03-18 14:27 UTC
