### ISSUE TITLE
Reference Browser not supported unless --firefox-apk-component is set

### ISSUE THREAD

**Issue by Rob--W** [mozilla/web-ext#2041] opened 2020-10-05 16:39 UTC
### Is this a feature request or a bug?
Bug

### What is the current behavior?
Upon running the following:

```
web-ext run -t firefox-android --android-device=DEVICEID_HERE  --firefox-apk=org.mozilla.reference.browser
```

... the Reference Browser app (https://github.com/mozilla-mobile/reference-browser) is not launched and the following error is displayed:

> Error: Activity class {org.mozilla.reference.browser/org.mozilla.reference.browser.App} does not exist.

### What is the expected or desired behavior?
The reference browser should be launched. As a work-around, I have to add ` --firefox-apk-component=BrowserActivity` .

To fix this, we would have to recognize the special component at https://github.com/mozilla/web-ext/blob/82c4250935bf7c5954ed2482447669628b3aaaa5/src/util/adb.js#L314-L315

### Version information (for bug reports)
````
node --version && npm --version && web-ext --version
````

> v14.13.0
6.14.7
5.2.0

**Comment by rpl** [comment] 2020-10-15 13:29
mentor: @rpl

**Comment by krush11** [comment] 2020-10-15 15:19
Hi, i would llike to work on this but i as this would be my first contribution i would need help. How do i pinpoint the file where i might need to make changes?

**Comment by rpl** [comment] 2020-10-15 17:20
@krush11 Welcome!
@Rob--W did link that in the issue description.

Given that this would be your first contribution, I suggest you to also:
- take a look to the contribution guide here: https://github.com/mozilla/web-ext/blob/master/CONTRIBUTING.md
- try to run the existing tests before making any chance, to be sure that the development environment is worked correctly

Let us know if you get stuck or have some questions to ask

**Comment by krush11** [comment] 2020-10-16 10:56
i have built and run tests. But i have no idea how to proceed. Can you suggest me anything which might help?

**Comment by rpl** [comment] 2020-10-16 12:09
> i have built and run tests. But i have no idea how to proceed. Can you suggest me anything which might help?

@krush11 Sure thing

## Step 0: Be able to reproduce the issue

The first step to fix an issue is always "understanding it and be sure to know how to reproduce it".

In this case the issue is related to `web-ext run` used to run an extension on the "Reference Browser" android application.

And so I would start by trying to:
- install the "Reference Browser" on an android device or android emulator
- create a small test extension or use one of the simple examples in the mdn/webextensions-examples repository (e.g. borderify is a small one that you could use: https://github.com/mdn/webextensions-examples/tree/master/borderify)
- try to run the test extension on the "Reference Browser" application using the `web-ext run` command in the issue description 

you can (and should) learn more about the `web-ext run` cli option available from the following two doc pages:
- https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext
- https://extensionworkshop.com/documentation/develop/web-ext-command-reference/

Be sure to be able to reproduce the issue as described by Rob, and then the workaround described in the issue description (and start question yourself about why that works).

## Step 1.1: Learn more about the domain (technical concepts, jargon etc) if needed

There may be concepts or jargon that you may not know yet, especially if you have never looked into how android applications work (e.g. what is an apk? what is an apk component?), you may gave a look to some android developer docs to try to find the meaning of those concepts on your own first.

Learning how to look for answers is an important skill to develop, as mentors it is important that we give you the chance to try to look for those as many answers as possible on your own, and providing all answers upfront would prevent you from trying and get better over the time.

If you are unable to find a good answer or one that does really convince you, you shouldn't feel guilty, it is pretty normal in the initial learning phases. Feel free to ask (hopefully specific enough) questions and we will be happy to provide you the details that you didn't figure out yet.

## Step 1.2: "Read the source, Luke!"

(I couldn't resist, I had to quote "star wars" here :-))

Another important step is "finding out which part of the source code of the project is providing the feature related to the issue you are looking into", read it and try to understand as much of that source code as possible (and figure out what other source modules may be useful to read).

The following source files are some of the ones that will be useful to read and understand to fix this particular issue (with associated the "questions" that I would ask myself while looking for fixing this issue if I didn't knew the project source code already, and which are the related source code that should "answer those questions"):

- where is the source code that provide the communication channel between the developer machine and the android device or emulator? https://github.com/mozilla/web-ext/blob/master/src/util/adb.js
- where is the source code of the components that orchestrate the steps needed to run an android app, install the extension into it and then reload automatically when the source changes? https://github.com/mozilla/web-ext/blob/master/src/extension-runners/firefox-android.js
- where the `web-ext run` command is implemented? https://github.com/mozilla/web-ext/blob/master/src/cmd/run.js

## Step 1.3: "Figure out the change needed to fix the issue"

At this point, based on what you learned in the previous steps, it is time to figure out what kind of changes are needed.

With the help of the reading done in step 1.2 you should identify where you may want to try to apply some change and have an understanding of why, and so it is to try to apply the changes and they try to reproduce the issue again and see if the change did provide the behavior you expected.

Adding some logging and try to reproduce the issue again could help you to figure out some details that you may be initially missing.

This is also the phase where you should not fear to make changes that may break more instead of fixing the issue:

**never never never fear to break something source while experimenting locally**

experimenting is important even when it doesn't work, e.g. because it provides you a feedback on your level of understanding and it helps you to correct the picture that you are building in your mind about how the entire system works.

The more detailed and precise is the picture you got of the entire system, the easier will become for you to figure out what to do even before trying to apply any change. It does feel like magic initially but it is really not, it is just practice, that practice does train your brain to provide answers based on how your brain does picture the system you are working on.

## Closing notes

Give a try to these pointers and suggestions, and then feel free to ping me again to ask some more specific questions on the issues that you may be facing by doing so.

Happy hacking!

**Comment by ankushduacodes** [comment] 2020-11-01 21:07
@Rob--W I would like to take on this issue. Please let me know if I can.

**Comment by rpl** [comment] 2020-11-02 12:39
> @Rob--W @rpl I would like to take on this issue. Please let me know if I may.

Hi @ankushduacodes, 
Given that @krush11 didn't open a pull request and didn't ask for help over the last couple of weeks, I think that we can now consider this issue open for another contributor that is looking for a good first bug to work on.

The comments https://github.com/mozilla/web-ext/issues/2041#issuecomment-710007063, https://github.com/mozilla/web-ext/issues/2041#issuecomment-709472114 and https://github.com/mozilla/web-ext/issues/2041#issue-714995777 should provide you some pointers about how to get started.

Let us know if you have questions or you get stuck on some issue and you need help to figure it out.

**Comment by ankushduacodes** [comment] 2020-11-02 15:08
Thank you @rpl, I will take a look at this issue and let you know if I need any help.
Could you please assign me to this issue?
Thank you!...

**Comment by rpl** [comment] 2020-11-02 20:27
> Thank you @rpl, I will take a look at this issue and let you know if I need any help.
> Could you please assign me to this issue?
> Thank you!...

@ankushduacodes we don't usually assign the issue until a contributor did create a pull request, but in the meantime we do "gate keep" the issue to give the last contributor that wanted to work on the good first bug some time to dig into the issue and create the PR (usually a couple of weeks), asking new contributors to look to one of the other good first bugs in the meantime.

**Comment by ankushduacodes** [comment] 2020-11-05 21:35
@rpl When I try to run command `npm start` I get an error:
```  1) web-ext imported as a library
       "after all" hook for "can be imported as a CommonJS module":
     Error: Command failed: /usr/local/bin/npm unlink
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ankushdua/.npm/_logs/2020-11-05T21_33_14_911Z-debug.log

      at checkExecSyncError (child_process.js:616:11)
      at execSync (child_process.js:652:15)
      at Context.<anonymous> (tests/functional/test.lib.imports.js:30:5)
      at processImmediate (internal/timers.js:461:21)
```

Is this something I should be aware of?

**Comment by ankushduacodes** [comment] 2020-11-05 23:38
@rpl I have correctly installed and ran the tests. the tests are running fine.
I tried to follow the steps outlined in this [comment](https://github.com/mozilla/web-ext/issues/2041#issuecomment-710007063).
I have downloaded the extension and tried to run on normal firefox (ie. stable version of firefox). and it runs as expected as it adds 5px red border around any website ending with .mozilla.org.
I have also installed the reference browser on my device using the guide provided by reference browser [repo](https://github.com/mozilla-mobile/reference-browser#test-channel-on-google-play-store).
when I try to run the `web-ext run -t firefox-android` it gives me adb error: 
`s: No adb executable has been found. You can Use --adb-bin, --adb-host/--adb-port to configure it manually if needed.`

What is the step that I am doing wrong here?

**Comment by rpl** [comment] 2020-11-06 10:18
> @rpl I have correctly installed and ran the tests. the tests are running fine.
> I tried to follow the steps outlined in this [comment](https://github.com/mozilla/web-ext/issues/2041#issuecomment-710007063).
> I have downloaded the extension and tried to run on normal firefox (ie. stable version of firefox). and it runs as expected as it adds 5px red border around any website ending with .mozilla.org.
> I have also installed the reference browser on my device using the guide provided by reference browser [repo](https://github.com/mozilla-mobile/reference-browser#test-channel-on-google-play-store).
> when I try to run the `web-ext run -t firefox-android` it gives me adb error:
> `s: No adb executable has been found. You can Use --adb-bin, --adb-host/--adb-port to configure it manually if needed.`
> 
> What is the step that I am doing wrong here?

@ankushduacodes You are just missing the adb tool executable. My apologies, I should have explicitly mention and link in my initial guidance comment this additional doc page (which provides more details about how to setup a developer machine for android, in particular to install adb):

https://extensionworkshop.com/documentation/develop/developing-extensions-for-firefox-for-android/#set-up-your-computer-and-android-emulator-or-device

`adb` means "Android Debug Bridge" and it is the tool that web-ext does use internally to interact with the android device or emulator (to learn more about what adb is you may also want to look to the following doc page: https://developer.android.com/studio/command-line/adb).

**Comment by ankushduacodes** [comment] 2020-11-07 04:23
@rpl I was able to set up the adb and I actually was able to accidentally reproduce the issue on hand, as when I tried to run web-ext using following command `web-ext run -s /Users/ankushdua/Documents/GitHub/web-ext/borderify -t firefox-android --android-device <DEVICE ID> --firefox-apk org.mozilla.reference.browser`

I gave me the exact error that is mentioned in the issue description.
but when I ran `web-ext run -s /Users/ankushdua/Documents/GitHub/web-ext/borderify -t firefox-android --android-device <DEVICE ID> --firefox-apk org.mozilla.reference.browser --firefox-apk-component=BrowserActivity`
Every thing worked fine.

So now, my step would be to look for the how and why apk-component is used, Right?

**Comment by ankushduacodes** [comment] 2020-11-08 07:34
@rpl So, Following is how I have thought of solving this issue.
```js
if (browser === 'org.mozilla.reference.browser' && apkComponent === '.App') {
          apkComponent = '.BrowserActivity';
        }
```
above lines of code were added after this line https://github.com/mozilla/web-ext/blob/82c4250935bf7c5954ed2482447669628b3aaaa5/src/util/adb.js#L324

I know this is a hackish way to solve the problem, Any thoughts or suggestions?

**Comment by rpl** [comment] 2020-11-09 10:49
> @rpl So, Following is how I have thought of solving this issue.
> 
> https://github.com/mozilla/web-ext/blob/82c4250935bf7c5954ed2482447669628b3aaaa5/src/util/adb.js#L323-L329
> ... 
> I know this is a hackish way to solve the problem, Any thoughts or suggestions?


I think that something like the following would do and be a bit less hacky:

```js
if (!apkComponent) {
  if (apk === 'org.mozilla.reference.browser') {
    apkComponent = '.BrowserActivity';
  } else {
    apkComponent = '.App';
  }
}
```

Or even better, we could create an explicit map of default apkComponent values keyed by apk
(which may make it easier to manage the mapping over the time and make it a bit more explicit)  e.g.:

```js
// In src/firefox/package-identifiers.js something like:
export const defaultApkComponents = {
  'org.mozilla.reference.browser': '.BrowserActivity',
}; 

// then in src/utils/adb.js
import packageIdentifiers, {defaultApkComponents} from '../firefox/package-identifiers';

...

  if (!apkComponent) {
    if (defaultApkComponents[apk]) {
       apkComponent = defaultApkComponents[apk];
    } else {
      // Fallback to .App by default.
      apkComponent = '.App';
    }
  }
```

I think that I like this last approach. Let me know how that sounds to you.

> One more question: How do I get log.debug() statements to print on the console?

The debug logs are printed on the console while web-ext is running in verbose mode, and so you should be able to see them printed in the console using the `--verbose` cli option.

**Comment by ankushduacodes** [comment] 2020-11-09 11:10
@rpl I am very new to javascript world, while I knew this way of importing and export modules, it never crossed my mind. Looking at the codebase of web-ext, its very explicit in a sense that there are not many string literal comparisons. That's why I was feeling like my solution was going to work but wasn’t up to the standards.

Thank you for making me understand this!....😄

**Closed** 2020-11-13 11:32 UTC
Labels: contrib: good first bug, contrib: mentor assigned
