### ISSUE TITLE
Use web-ext to get build for Google Chrome

### ISSUE THREAD

**Issue by Kazem-ma79** [mozilla/web-ext#2265] opened 2021-06-14 16:42 UTC
### Is this a feature request or a bug?
Question

### What is the current behavior?
I'm trying to get output for Chrome with this command:
`web-ext build --overwrite-dest --target chromium --source-dir ./chrome/`
But getting error: unknown argument target

**Comment by Rob--W** [comment] 2021-06-14 21:00
What do you mean by a build for Chrome, and what would you like to do with it? A crx file? A zip file to upload to the Chrome Web Store? Something that can be loaded as an unpacked extension via Chrome?

**Comment by rpl** [comment] 2021-06-16 10:06
`--target` is an option of `web-ext run` and allows to run the extension on chrome during development.

`web-ext build` does just zip the extension directory and it does not support the `--target` option (as the error also suggests).

Then the developer may upload the zip file generated by `web-ext build` to the appropriate extension store, e.g. addons.mozilla.org to get it converted into a signed xpi file that can be installed on Firefox or `chrome.google.com/webstore/` to get it converted into a signed crx file that can be installed on Chrome.

I'm closing this as invalid, given that this is the expected behavior.

Nevertheless let us know if the pointers provided above did not let you understand yet the reason behind the error.

**Closed by rpl** 2021-06-16 10:06 UTC
