### ISSUE TITLE
"web-ext sign" command is timing out

### ISSUE THREAD

**Issue by forcepointendpoint** [mozilla/web-ext#1773] opened 2019-12-03 19:31 UTC
### What is the current behavior?
Ever since 11/21/2019, we have been seeing the issue frequently. The sign command has only succeeded about 4 times out of 40 test attempts. 
> web-ext sign --api-key=user:******* --api-secret=********
> Building web extension from C:\Users\Administrator.DELL123456\Desktop\New folder\dlpext\dlpext
> Validating add-on […]
> 
> sign: Error: Validation took too long to complete; last status: {“guid":"fpdlpffext3@forcepoint.com”,“active”:false,“automated_signing”:true,“url”:"https://addons.mozilla.org/api/v3/addons/fpdlpffext3@forcepoint.com/versions/8.1.4402.102/uploads/12b670d85045423a9f29c791d2ac187e/",“files”:[{“download_url”:“https://addons.mozilla.org/api/v3/file/3460180/forcepoint_endpoint-8.1.4402.102-an+fx.xpi?src=api”,“hash”:“sha256:2e724be07ada0ca6f94627379f7e4a7fb9926ca34d429c8b031bcf20428cd961”,“signed”:false}],“passed_review”:false,“pk”:"12b670d85045423a9f29c791d2ac187e…
> at Timeout._onTimeout (C:\Program Files\nodejs\web-ext-master\node_modules\sign-addon\dist\webpack:\src\amo-client.js:222:16)
> at ontimeout (timers.js:386:14)
> at tryOnTimeout (timers.js:250:5)
> at Timer.listOnTimeout (timers.js:214:5)

Also seeing this error in the console:

> Potentially unhandled rejection [1] Error: connect ETIMEDOUT 34.215.211.225:443 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14)

Pinging addons.mozilla.org returns that same IP address.

### Version information (for bug reports)

* **Firefox version**: 71
* **Your OS and version**: Windows 10 1903
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
node: v12.13.1
npm: 6.12.1
web-ext: 3.2.1
[webext_sign_verbose.txt](https://github.com/mozilla/web-ext/files/3918316/webext_sign_verbose.txt)

````
https://discourse.mozilla.org/t/web-ext-sign-command-is-timing-out/49670

**Comment by jca** [comment] 2019-12-05 12:56
Defaults should be fixed to work properly, but as a workaround you can use
 `web-ext sign --timeout=300000` to set a longer timeout (5 minutes). This works for me

You can see `web-ext help sign` for more details

**Comment by diox** [comment] 2019-12-05 13:21
Default timeout in `web-ext` 3.2.1 should 15 minutes. Setting it to 5 is reducing it (and dramatically increases chances of a timeout).

In any case the timeout encountered here seems to be a network one, not just an issue with signing taking too long. This is weird, not sure what to say besides check how reliable your connection is...

**Comment by rpl** [comment] 2019-12-05 14:31
@forcepointendpoint is the project including a web-ext config file with a timeout value in it?
In version 3.2.1 we backported a fix applied to move recent sign-addon package versions, which use a longer timeout by default but only if there isn't one specified (e.g. from the command line or a config file):

https://github.com/mozilla/web-ext/commit/7aa8660f308fc38069c3e57eafb138e47adb949f

**Comment by jca** [comment] 2019-12-08 11:19
@diox , I actually used 1 hour but thought this was overkill so I put 5 minutes in my comment. Thanks for pointing out the default. Since your comment I didn't experience the issue, but this morning I got a timeout (without any timeout configured) after slightly more than 2 minutes:

```
Validating add-on [............................................................]

Error: Validation took too long to complete; last status: {"guid":"***","active":false,"automated_signing":true,"url":"*****","files":[{"download_url":"?src=api","hash":"sha256:****","signed":false}],"passed_review":false,"pk":"*****","processed":true,"reviewed":false,"valid":true,"validat...
    at Timeout._onTimeout (/Users/admin/Workspaces/customers/ext/extension/build/node_modules/sign-addon/dist/webpack:/src/amo-client.js:232:16)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)

real	2m4.912s
user	0m1.561s
sys	0m0.377s

XPI signing failed!

node --version && npm --version && ./node_modules/.bin/web-ext --version
node: v13.2.0
npm: 6.13.1
web-ext: 3.2.1
```

**Comment by forcepointendpoint** [comment] 2019-12-12 00:05
@rpl , @jca , 
During my troubleshooting last week, I've increased the timeout to 20 minutes and even 1 hour, but the issue still persisted. I have not defined a timeout value in any config files. 

The process was working fine for ~2 years until 11/21/2019, when it started failing almost every attempt. This date coincides with the workflow changes made to AMO upload process. 

When I sign into AMO, I do see that my extension has passed verification, but web-ext command still times out.

**Comment by YouthLab** [comment] 2019-12-16 06:34
@rpl
@jca
@forcepointendpoint 
I have meet the same issue as @forcepointendpoint described.

**Comment by rpl** [comment] 2019-12-16 17:36
@forcepointendpoint @jca @YouthLab I'm wondering if the same issue is also reproducible on the web-ext master branch (where the sign-addon dependency has been upgraded instead of backporting the longer timeout value).

would you mind to double-check if the same issue can be triggered with the updated sign-addon dependency? (by building and then using web-ext directly from this repo)

**Comment by YouthLab** [comment] 2019-12-17 01:54
@forcepointendpoint @jca @rpl 
It seems like that this problem has been fixed on master branch！
```sh
$ web-ext --version
master-7ee3c44365df645e49ef739590b2571c74c6d184
```
Thanks for your help! @rpl

**Comment by forcepointendpoint** [comment] 2019-12-17 19:22
@rpl @YouthLab 
The master branch build works for me also. Is the master branch build safe to use for the long term? When will the related fix be included in an official web-ext release version?

**Comment by rpl** [comment] 2019-12-24 14:13
Closing (we just release the master branch on npm as v4.0.0)

**Closed by rpl** 2019-12-24 14:13 UTC
Labels: needs: info

**Comment by sublimator** [comment] 2022-09-16 03:05
I'm still getting a lot of timeouts as of Sept 2022

**Comment by praveen-zluri** [comment] 2023-02-20 12:53
Dude, it working fine until December' 2022. Suddenly, since 3rd week of Feb' 22, it shows all kinds error such as `timeout error`, `eaddrnotfound`, and the signing process runs forever.
