### ISSUE TITLE
Don't color output (I can't read it)

### ISSUE THREAD

**Issue by hachi** [mozilla/web-ext#3222] opened 2024-08-13 08:50 UTC
### Is this a feature request or a bug?

Honestly, I consider it a bug, I have my terminal colors set for readability, but web-ext is overriding that.

### What is the current behavior?

Text output from web-ext is in (often red

### What is the expected or desired behavior?

Text should use default colors in the terminal you are using.

### Version information (for bug reports)
```
node --version && npm --version && web-ext --version
```
v20.16.0
10.8.1
8.2.0

**Comment by Rob--W** [comment] 2024-08-13 09:41
Could you share a screenshot? I don't think that we explicitly set colors. We write plain lines at

https://github.com/mozilla/web-ext/blob/244aeb3f68868455d2d81cbb16a0dbb80b459a64/src/util/logger.js#L28

**Comment by hachi** [comment] 2024-08-14 12:18
![Screenshot from 2024-08-14 05-17-35](https://github.com/user-attachments/assets/edfc1ba4-31cc-499b-810f-cdae29fb7b1b)

**Comment by fregante** [comment] 2024-08-23 12:51
I can confirm the issue. I can repro the issue all the way to web-ext v1. I think the CLI harness automatically colors `stderr` as red, which makes somewhat sense.

In this case the exit code is 1 because no commands were specified, so the entire output is printed as an error.




> I have my terminal colors set for readability,

If you can't read it, you need to improve the colors. Red text is not unusual on CLI and it's _somewhat readable_ in my default palette. Of course this is not to say that the issue isn't valid: so much red text doesn't have the best contrast.

<img width="572" alt="Screenshot" src="https://github.com/user-attachments/assets/971e3edf-30ad-4afd-a0ff-d4125c475689">

**Comment by fregante** [comment] 2024-08-23 12:53
When the exit code is 0, the color is correct:

<img width="575" alt="Screenshot 10" src="https://github.com/user-attachments/assets/e049f079-db63-46b6-a8b3-17afec2dda25">

**Comment by hachi** [comment] 2024-08-23 17:41
I agree with you on all points, I need to fix my colors to be better... and I would politely be asking for no command supplied to not color the help output red.

**Comment by fregante** [comment] 2024-08-24 05:52
FWIW `addons-linter` has the same behavior

**Comment by Rob--W** [comment] 2024-08-30 13:06
This issue is happening because `yargs` uses `console.error()`
- https://github.com/yargs/yargs/blob/0c95f9c79e1810cf9c8964fbf7d139009412f7e7/lib/usage.ts#L64-L65
- https://github.com/yargs/yargs/blob/0c95f9c79e1810cf9c8964fbf7d139009412f7e7/lib/usage.ts#L622-L623

and Node.js colors `console.error()`. Minimal reproduction:

```sh
node -e 'console.error("is this red?")'
```

Node.js supports disabling colors by setting the `NO_COLOR` or `NODE_DISABLE_COLORS` environment variable, documented at https://nodejs.org/api/cli.html#no_colorany

```sh
NO_COLOR=1 node -e 'console.error("is this red?")'
```

or in your interactive shell:

```sh
export NODE_DISABLE_COLORS=1
node -e 'console.error("is this red?")'
```

Since this is not an issue with web-ext itself, but general Node.js behavior, I'm going to close this issue.
IMO the real fix is not to disable the colors, but to configure your shell's color scheme such that "red" is readable.

**Closed by Rob--W** 2024-08-30 13:06 UTC
