### ISSUE TITLE
web-ext run is not working correctly for firefox 77.0.1

### ISSUE THREAD

**Issue by markylaing** [mozilla/web-ext#1932] opened 2020-06-16 11:42 UTC
### Is this a feature request or a bug?
This is a bug.

### What is the current behavior?

After the latest firefox update, the following command failed to run:
`web-ext run --verbose --source-dir=dist/browser-plugin`

The following logs were outputted:
```

> browser-plugin@0.1.0 start /home/mark.laing@medcat.local/projects/collaboratory/browser-plugin
> web-ext run --verbose --source-dir=dist/browser-plugin

[program.js][info] Version: 4.1.0
[program.js][debug] Discovering config files. Set --no-config-discovery to disable
[config.js][debug] Discovered config "/home/mark.laing@medcat.local/.web-ext-config.js" does not exist or is not readable
[config.js][debug] Discovered config "/home/mark.laing@medcat.local/projects/collaboratory/browser-plugin/web-ext-config.js" does not exist or is not readable
[program.js][info] Applying config file: ./package.json
[config.js][debug] Loading JS config file: "/home/mark.laing@medcat.local/projects/collaboratory/browser-plugin/package.json" (resolved to "/home/mark.laing@medcat.local/projects/collaboratory/browser-plugin/package.json")
[config.js][debug] Looking for webExt key inside package.json file
[config.js][debug] Config file /home/mark.laing@medcat.local/projects/collaboratory/browser-plugin/package.json did not define any options. Did you set module.exports = {...}?
[cmd/run.js][info] Running web extension from /home/mark.laing@medcat.local/projects/collaboratory/browser-plugin/dist/browser-plugin
[util/manifest.js][debug] Validating manifest at /home/mark.laing@medcat.local/projects/collaboratory/browser-plugin/dist/browser-plugin/manifest.json
[extension-runners/firefox-desktop.js][debug] Creating new Firefox profile
[firefox/index.js][debug] Running Firefox with profile at /tmp/3fba173e-2956-4967-af4b-af945740987c
[firefox/index.js][debug] Executing Firefox binary: /usr/bin/firefox
[firefox/index.js][debug] Firefox args: -start-debugger-server 42119 -foreground -no-remote -profile /tmp/3fba173e-2956-4967-af4b-af945740987c
[firefox/index.js][info] Use --verbose or open Tools > Web Developer > Browser Console to see logging
[firefox/remote.js][debug] Connecting to the remote Firefox debugger
[firefox/remote.js][debug] Connecting to Firefox on port 42119
[firefox/remote.js][debug] Retrying Firefox (0); connection error: Error: connect ECONNREFUSED 127.0.0.1:42119
[firefox/remote.js][debug] Connecting to Firefox on port 42119
[firefox/remote.js][debug] Retrying Firefox (1); connection error: Error: connect ECONNREFUSED 127.0.0.1:42119
[firefox/remote.js][debug] Connecting to Firefox on port 42119
[firefox/remote.js][debug] Retrying Firefox (2); connection error: Error: connect ECONNREFUSED 127.0.0.1:42119
[firefox/remote.js][debug] Connecting to Firefox on port 42119
[firefox/remote.js][debug] Retrying Firefox (3); connection error: Error: connect ECONNREFUSED 127.0.0.1:42119
[firefox/remote.js][debug] Connecting to Firefox on port 42119
[firefox/index.js][debug] Firefox stdout: Started devtools server on 42119
[firefox/remote.js][debug] Retrying Firefox (4); connection error: Error: connect ECONNREFUSED 127.0.0.1:42119
[firefox/remote.js][debug] Connecting to Firefox on port 42119
[firefox/remote.js][debug] Connected to the remote Firefox debugger on port 42119
[firefox/remote.js][debug] listTabs returned a falsey addonsActor: undefined
[extension-runners/firefox-desktop.js][debug] Caught: c: This is an older version of Firefox that does not provide an add-ons actor for remote installation. Try Firefox 49 or higher.
[program.js][error] 
o: Temporary add-on installation is not supported in this version of Firefox (you need Firefox 49 or higher). For older Firefox versions, use --pre-install
    at c.startFirefoxInstance (/home/mark.laing@medcat.local/projects/collaboratory/browser-plugin/node_modules/web-ext/dist/web-ext.js:1:51601)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

[program.js][debug] Command executed: run
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! browser-plugin@0.1.0 start: `web-ext run --verbose --source-dir=dist/browser-plugin`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the browser-plugin@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mark.laing@medcat.local/.npm/_logs/2020-06-16T11_24_33_276Z-debug.log
```

### What is the expected or desired behavior?
Would expect 

### Version information (for bug reports)

* **Firefox version**: 77.0.1
* **Your OS and version**: Ubuntu 20.04
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
v12.16.2
6.14.4
4.1.0

**Comment by Rob--W** [comment] 2020-06-16 11:44
You should update to web-ext 4.2.0.

Duplicate of #1921, #1884, fixed by #1886

**Closed by Rob--W** 2020-06-16 11:44 UTC
