### ISSUE TITLE
"web-ext run --target firefox-android" crash

### ISSUE THREAD

**Issue by avi12** [mozilla/web-ext#2185] opened 2021-03-08 00:01 UTC
### Is this a feature request or a bug?
Bug

### What is the current behavior?

I cannot run
```shell
web-ext run --no-config-discovery --start-url=URL --source-dir dist --verbose --target firefox-android --adb-device 1af587c730057ece --firefox-apk org.mozilla.fenix
```
I get instead
```log
[program.js][info] Version: 5.5.0
[program.js][debug] Not discovering config files
[cmd/run.js][info] Running web extension from C:\repositories\extensions\youtube-speed-control\dist
[util/manifest.js][debug] Validating manifest at C:\repositories\extensions\youtube-speed-control\dist\manifest.json
[extension-runners/firefox-android.js][warn] The Firefox for Android target does not support --start-url
[extension-runners/firefox-android.js][debug] Listing android devices
[util/adb.js][debug] Listing android devices
[extension-runners/firefox-android.js][info] Selected ADB device: 1af587c730057ece
[util/adb.js][debug] Listing installed Firefox APKs on 1af587c730057ece
[util/adb.js][debug] Run adb shell command on 1af587c730057ece: ["pm","list","packages"]
[extension-runners/firefox-android.js][debug] Selected Firefox for Android APK: org.mozilla.fenix
[extension-runners/firefox-android.js][debug] Discovering Android version for 1af587c730057ece...
[util/adb.js][debug] Run adb shell command on 1af587c730057ece: ["getprop","ro.build.version.sdk"]
[extension-runners/firefox-android.js][debug] Detected Android version 29
[extension-runners/firefox-android.js][debug] Checking read/write permissions needed for web-exton org.mozilla.fenix...
[util/adb.js][debug] Run adb shell command on 1af587c730057ece: ["pm","dump","org.mozilla.fenix"]
[extension-runners/firefox-android.js][info] Stopping existing instances of org.mozilla.fenix...
[util/adb.js][debug] Run adb shell command on 1af587c730057ece: ["am","force-stop","org.mozilla.fenix"]
[extension-runners/firefox-android.js][debug] Preparing a temporary profile for org.mozilla.fenix...
[util/adb.js][debug] Checking adb device for existing web-ext artifacts dirs
[extension-runners/firefox-android.js][warn] Old artifacts directories have been found on 1af587c730057ece device. Use --adb-remove-old-artifacts to remove them automatically.
[util/adb.js][debug] Run adb shell command on 1af587c730057ece: "test -d /sdcard/web-ext-artifacts-1615161049187 ; echo $?"
[util/adb.js][debug] Run adb shell command on 1af587c730057ece: ["mkdir","-p","/sdcard/web-ext-artifacts-1615161049187"]
[util/adb.js][debug] Run adb shell command on 1af587c730057ece: ["mkdir","-p","/sdcard/web-ext-artifacts-1615161049187/profile"]
[util/adb.js][debug] Pushing C:\Users\avi12\AppData\Local\Temp\fa88ad17-d0c3-4205-9e7b-2379d6af8d3f\user.js to /sdcard/web-ext-artifacts-1615161049187/profile/user.js on 1af587c730057ece
[extension-runners/firefox-android.js][debug] Created temporary profile at /sdcard/web-ext-artifacts-1615161049187/profile.
[extension-runners/firefox-android.js][info] Starting org.mozilla.fenix...
[extension-runners/firefox-android.js][debug] Using profile /sdcard/web-ext-artifacts-1615161049187/profile (ignored by Fenix)
[util/adb.js][debug] Starting org.mozilla.fenix on 1af587c730057ece
[util/adb.js][info] Waiting for org.mozilla.fenix Remote Debugging Server...
Make sure to enable "Remote Debugging via USB" from Settings -> Developer Tools if it is not yet enabled.
[util/adb.js][debug] Run adb shell command on 1af587c730057ece: ["cat","/proc/net/unix"]
[util/temp-dir.js][debug] Created temporary directory: C:\Users\avi12\AppData\Local\Temp\tmp-web-ext--36672-r9RYwriAKy0T
[util/file-filter.js][debug] Resolved path **/*.xpi with sourceDir C:\repositories\extensions\youtube-speed-control\dist to C:\repositories\extensions\youtube-speed-control\dist\**\*.xpi
[util/file-filter.js][debug] Resolved path **/*.zip with sourceDir C:\repositories\extensions\youtube-speed-control\dist to C:\repositories\extensions\youtube-speed-control\dist\**\*.zip
[util/file-filter.js][debug] Resolved path **/.* with sourceDir C:\repositories\extensions\youtube-speed-control\dist to C:\repositories\extensions\youtube-speed-control\dist\**\.*
[util/file-filter.js][debug] Resolved path **/.*/**/* with sourceDir C:\repositories\extensions\youtube-speed-control\dist to C:\repositories\extensions\youtube-speed-control\dist\**\.*\**\*
[util/file-filter.js][debug] Resolved path **/node_modules with sourceDir C:\repositories\extensions\youtube-speed-control\dist to C:\repositories\extensions\youtube-speed-control\dist\**\node_modules
[util/file-filter.js][debug] Resolved path **/node_modules/**/* with sourceDir C:\repositories\extensions\youtube-speed-control\dist to C:\repositories\extensions\youtube-speed-control\dist\**\node_modules\**\*
[cmd/build.js][info] Building web extension from C:\repositories\extensions\youtube-speed-control\dist
[util/manifest.js][debug] Validating manifest at C:\repositories\extensions\youtube-speed-control\dist\manifest.json
[util/file-filter.js][debug] Resolved path C:\repositories\extensions\youtube-speed-control\dist\app.js with sourceDir C:\repositories\extensions\youtube-speed-control\dist to C:\repositories\extensions\youtube-speed-control\dist\app.
js
[util/file-filter.js][debug] Resolved path C:\repositories\extensions\youtube-speed-control\dist\background.html with sourceDir C:\repositories\extensions\youtube-speed-control\dist to C:\repositories\extensions\youtube-speed-control\
dist\background.html
[util/file-filter.js][debug] Resolved path C:\repositories\extensions\youtube-speed-control\dist\background.js with sourceDir C:\repositories\extensions\youtube-speed-control\dist to C:\repositories\extensions\youtube-speed-control\di
st\background.js
[util/file-filter.js][debug] Resolved path C:\repositories\extensions\youtube-speed-control\dist\content.js with sourceDir C:\repositories\extensions\youtube-speed-control\dist to C:\repositories\extensions\youtube-speed-control\dist\
content.js
[util/file-filter.js][debug] Resolved path C:\repositories\extensions\youtube-speed-control\dist\images with sourceDir C:\repositories\extensions\youtube-speed-control\dist to C:\repositories\extensions\youtube-speed-control\dist\imag
es
[util/file-filter.js][debug] Resolved path C:\repositories\extensions\youtube-speed-control\dist\index.html with sourceDir C:\repositories\extensions\youtube-speed-control\dist to C:\repositories\extensions\youtube-speed-control\dist\
index.html
[util/file-filter.js][debug] Resolved path C:\repositories\extensions\youtube-speed-control\dist\manifest.json with sourceDir C:\repositories\extensions\youtube-speed-control\dist to C:\repositories\extensions\youtube-speed-control\di
st\manifest.json
[util/file-filter.js][debug] Resolved path C:\repositories\extensions\youtube-speed-control\dist\yt-speed-control-script-to-inject.js with sourceDir C:\repositories\extensions\youtube-speed-control\dist to C:\repositories\extensions\y
outube-speed-control\dist\yt-speed-control-script-to-inject.js
[util/file-filter.js][debug] Resolved path C:\repositories\extensions\youtube-speed-control\dist\images\icon-128.png with sourceDir C:\repositories\extensions\youtube-speed-control\dist to C:\repositories\extensions\youtube-speed-cont
rol\dist\images\icon-128.png
[util/file-filter.js][debug] Resolved path C:\repositories\extensions\youtube-speed-control\dist\images\icon-16.png with sourceDir C:\repositories\extensions\youtube-speed-control\dist to C:\repositories\extensions\youtube-speed-contr
ol\dist\images\icon-16.png
[util/file-filter.js][debug] Resolved path C:\repositories\extensions\youtube-speed-control\dist\images\icon-19.png with sourceDir C:\repositories\extensions\youtube-speed-control\dist to C:\repositories\extensions\youtube-speed-contr
ol\dist\images\icon-19.png
[util/file-filter.js][debug] Resolved path C:\repositories\extensions\youtube-speed-control\dist\images\icon-24.png with sourceDir C:\repositories\extensions\youtube-speed-control\dist to C:\repositories\extensions\youtube-speed-contr
ol\dist\images\icon-24.png
[util/file-filter.js][debug] Resolved path C:\repositories\extensions\youtube-speed-control\dist\images\icon-256.png with sourceDir C:\repositories\extensions\youtube-speed-control\dist to C:\repositories\extensions\youtube-speed-cont
rol\dist\images\icon-256.png
[util/file-filter.js][debug] Resolved path C:\repositories\extensions\youtube-speed-control\dist\images\icon-32.png with sourceDir C:\repositories\extensions\youtube-speed-control\dist to C:\repositories\extensions\youtube-speed-contr
ol\dist\images\icon-32.png
[util/file-filter.js][debug] Resolved path C:\repositories\extensions\youtube-speed-control\dist\images\icon-38.png with sourceDir C:\repositories\extensions\youtube-speed-control\dist to C:\repositories\extensions\youtube-speed-contr
ol\dist\images\icon-38.png
[util/file-filter.js][debug] Resolved path C:\repositories\extensions\youtube-speed-control\dist\images\icon-64.png with sourceDir C:\repositories\extensions\youtube-speed-control\dist to C:\repositories\extensions\youtube-speed-contr
ol\dist\images\icon-64.png
[util/file-filter.js][debug] Resolved path C:\repositories\extensions\youtube-speed-control\dist\images\icon-48.png with sourceDir C:\repositories\extensions\youtube-speed-control\dist to C:\repositories\extensions\youtube-speed-contr
ol\dist\images\icon-48.png
[util/file-filter.js][debug] Resolved path C:\repositories\extensions\youtube-speed-control\dist\images\icon-96.png with sourceDir C:\repositories\extensions\youtube-speed-control\dist to C:\repositories\extensions\youtube-speed-contr
ol\dist\images\icon-96.png
[extension-runners/firefox-android.js][debug] Uploading youtube_speed_control-1.1.2 on the android device
[util/adb.js][debug] Pushing C:\Users\avi12\AppData\Local\Temp\tmp-web-ext--36672-r9RYwriAKy0T\youtube_speed_control-1.1.2.zip to /sdcard/web-ext-artifacts-1615161049187/youtube_speed_control-1.1.2.xpi on 1af587c730057ece
[extension-runners/firefox-android.js][debug] Upload completed: /sdcard/web-ext-artifacts-1615161049187/youtube_speed_control-1.1.2.xpi
[util/temp-dir.js][debug] Removing temporary directory: C:\Users\avi12\AppData\Local\Temp\tmp-web-ext--36672-r9RYwriAKy0T
[util/adb.js][info] Waiting for org.mozilla.fenix Remote Debugging Server...
Make sure to enable "Remote Debugging via USB" from Settings -> Developer Tools if it is not yet enabled.
[util/adb.js][debug] Run adb shell command on 1af587c730057ece: ["cat","/proc/net/unix"]
[extension-runners/firefox-android.js][debug] RDP Socket File selected: @org.mozilla.fenix/firefox-debugger-socket
[extension-runners/firefox-android.js][info] You can connect to this Android device on TCP port 49462
[util/adb.js][debug] Configuring ADB forward for 1af587c730057ece: localabstract:org.mozilla.fenix/firefox-debugger-socket -> tcp:49462
[firefox/remote.js][debug] Connecting to the remote Firefox debugger
[firefox/remote.js][debug] Connecting to Firefox on port 49462
[firefox/remote.js][debug] Connected to the remote Firefox debugger on port 49462
[program.js][error]
o: installTemporaryAddon: Error: Error: Could not install add-on at '/sdcard/web-ext-artifacts-1615161049187/youtube_speed_control-1.1.2.xpi': [Exception... "Component returned failure code: 0x80520015 (NS_ERROR_FILE_ACCESS_DENIED) [n
sIZipReader.open]"  nsresult: "0x80520015 (NS_ERROR_FILE_ACCESS_DENIED)"  location: "JS frame :: resource://gre/modules/addons/XPIInstall.jsm :: XPIPackage :: line 321"  data: no]
    at C:\repositories\extensions\youtube-speed-control\node_modules\.pnpm\web-ext@5.5.0\node_modules\web-ext\dist\web-ext.js:1:6007
    at Client.handleMessage (C:\repositories\extensions\youtube-speed-control\node_modules\.pnpm\@cliqz-oss\firefox-client@0.3.1\node_modules\@cliqz-oss\firefox-client\lib\client.js:162:7)
    at Client.readMessage (C:\repositories\extensions\youtube-speed-control\node_modules\.pnpm\@cliqz-oss\firefox-client@0.3.1\node_modules\@cliqz-oss\firefox-client\lib\client.js:221:10)
    at Client.onData (C:\repositories\extensions\youtube-speed-control\node_modules\.pnpm\@cliqz-oss\firefox-client@0.3.1\node_modules\@cliqz-oss\firefox-client\lib\client.js:187:16)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

[program.js][debug] Command executed: run
 ERROR  Command failed with exit code 1.
```
To be clear, I *did* enable the storage permission for Firefox Nightly

To reproduce, I created a branch in [my repository](https://github.com/avi12/youtube-speed-control/tree/web-ext-bug)

### Version information (for bug reports)

* **Firefox Nightly version**: 210307.17.01
* **Your OS and version**: Android 10
* Paste the output of these commands:

````
node --version; npm --version; web-ext --version

v14.16.0
7.6.1
5.5.0
````

**Comment by danielzgtg** [comment] 2021-03-13 09:04
Duplicate of #2173?

**Comment by avi12** [comment] 2021-03-13 12:38
Considering the error I'm getting compared to the one in the issue, my issue seems to be a duplicate indeed

**Closed** 2021-03-13 16:40 UTC
Labels: state: duplicate
