### ISSUE TITLE
`web-ext run` ignores `webExt.run.target` config in package.json

### ISSUE THREAD

**Issue by fregante** [mozilla/web-ext#2218] opened 2021-04-11 01:46 UTC
### Is this a feature request or a bug?

Bug

### What is the current behavior?

web-ext can be configured via the `webExt` property in package.json. This works well for `webExt.sourceDir` in my case, but `webExt.run.target` seems to be **read** and ignored.

By "read" I mean that the CLI actively complains if `target` isn't an array:

```
❯ web-ext run
Applying config file: ./package.json

s: The config file at ./package.json specified the type of "target" incorrectly as "string" (expected type "array")
```

but then it doesn't use the value.

### What is the expected or desired behavior?

This should open Chrome

```json
	"webExt": {
		"sourceDir": "distribution",
		"run": {
			"target": [
				"chromium"
			]
		}
	}
```

but only this does:

```
web-ext run --target chromium
```

And presumably via ENV as [documented](https://extensionworkshop.com/documentation/develop/web-ext-command-reference/#web-ext-run)

### Version information (for bug reports)

~~* **Firefox version**:~~
* **Your OS and version**: macOS 11.2.3
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
v15.12.0
7.6.3
6.0.0

**Comment by fregante** [comment] 2021-04-11 01:48
For the record, this is for a [Chrome-only extension](https://github.com/hankxdev/one-click-extensions-manager/issues/20#issuecomment-349408212)

**Comment by rpl** [comment] 2021-04-13 12:56
Closing as a duplicate of #1862 (which also contains some more details about the reasons behind the issue in https://github.com/mozilla/web-ext/issues/1862#issuecomment-604358932)

**Closed by rpl** 2021-04-13 12:56 UTC
