### ISSUE TITLE
Getting lint errors with manifest_version set to 3

### ISSUE THREAD

**Issue by akash07k** [mozilla/web-ext#2484] opened 2022-08-16 16:53 UTC
### Is this a feature request or a bug?
Bug

### What is the current behavior?

Getting error while linting if the manifest_version is set to 3:
`    "manifest_version": 3`,
Error:
```
Code           Message       Description            File   Line   Column
JSON_INVALID   "/manifest…   Your JSON file could                       
               _version"     not be parsed.                             
               must be <=                                               
               2                                                        
```
### What is the expected or desired behavior?
Lint command should not throw error
[log.txt](https://github.com/mozilla/web-ext/files/9352897/log.txt)

### Version information (for bug reports)

* **Firefox version**:
* **Your OS and version**:
* Paste the output of these commands:
Node V18.7.0
NPM V 8.15.0
web-ext V7.2.0
````
node --version && npm --version && web-ext --version
````

**Comment by Rob--W** [comment] 2022-08-16 17:22
Duplicate of #2379.

In short, use the `--firefox-preview` flag, which is also documented at https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/#turn-on-the-developer-preview

**Comment by Rob--W** [comment] 2022-08-16 17:22
Actually, the other one is about running, while this one is about the linter.

**Comment by akash07k** [comment] 2022-08-16 19:31
@Rob--W  Can we reopen this please?
I'm not using firefox, I'm using chromium.

**Comment by Rob--W** [comment] 2022-08-16 19:37
I have already re-opened this issue :)

**Comment by akash07k** [comment] 2022-08-17 06:55
not only linting, I'm unable to run my extension with firefox.
it says:
"invalid extension"
I've verified whole manifest, everything is fine.

**Comment by akash07k** [comment] 2022-08-17 06:58
[test.log](https://github.com/mozilla/web-ext/files/9357163/test.log)
I'm using Firefox developer edition with MV3 flags enabled

**Comment by Rob--W** [comment] 2022-08-18 13:11
@akash07k What version of Firefox are you using?
Could you share your manifest.json file?

**Comment by jsom** [comment] 2022-08-20 20:45
Hit the linting issue as well - `--firefox-preview` only seems to be applicable to `web-ext run` so far, but it's making it difficult to maintain an extension across Firefox and Chrome.
```
$ node_modules/.bin/web-ext --version
7.2.0

$ node_modules/.bin/web-ext lint -s src
Applying config file: ./package.json
Validation Summary:

errors          2
notices         0
warnings        0

ERRORS:

Code                    Message                                    Description                                        File            Line   Column
JSON_INVALID            "/manifest_version" must be <= 2           Your JSON file could not be parsed.
EXTENSION_ID_REQUIRED   The extension ID is required in Manifest   See https://mzl.la/3PLZYdo for more information.   manifest.json
                        Version 3 and above.

$ node_modules/.bin/web-ext lint --firefox-preview -s src
web-ext lint

Validate the extension source
<snip options dump>
Unknown arguments: firefox-preview, firefoxPreview
```

**Closed** 2022-09-09 17:47 UTC
Labels: enhancement, component: linting

**Comment by akash07k** [comment] 2022-09-09 19:17
Yep

**Comment by akash07k** [comment] 2022-10-11 07:27
Thanks :-)
