### ISSUE TITLE
"WebExtError: installTemporaryAddon: Error: Error: undefined passed where a value is required" when trying to test firefox android extension

### ISSUE THREAD

**Issue by MeikyuuTrader** [mozilla/web-ext#2502] opened 2022-09-08 03:13 UTC
### Is this a feature request or a bug?
Bug 

### What is the current behavior?

Trying to load in firefox extension for firefox nightly android. Running `web-ext run -t firefox-android --adb-device MY_DEVICE_ID --firefox-apk org.mozilla.fenix` from the firefox extension dev tutorial. 

Running the extension locally (on desktop) with `web-ext run` works fine and all behaviour is expected. I'm creating an extension for android and the web-ext android instructions return the title error. The folder contains the manifest.json, index.js, index.html and next/ folder. So the entire folder contains all the files required. 

Note that even when I remove all the other files except for the background script and update the manifest.json accordingly, the error still occurs.

### What is the expected or desired behavior?
Loads in firefox extension onto firefox nightly. 

### Version information (for bug reports)

* **Firefox version**: 106.0a1
* **Your OS and version**: Ubuntu 20.04.5 LTS
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version

v16.13.1
8.3.0
7.2.0
````

### Info

Running the extension locally (on desktop) with `web-ext run` works fine and all behaviour is expected. I'm creating an extension for android and the web-ext android instructions return the title error. 

```
manifest.json 
{
  "manifest_version": 2,
  "name": "extension name",
  "version": "1.0",
  "description": "description",
  "background": {
    "scripts": ["./index.js"],
    "persistent": true
  },
  "options_ui": {
    "page": "./index.html",
    "open_in_tab": true
  },
  "chrome_url_overrides": {
    "newtab": "./index.html"
  },
  "permissions": [
    "tabs",
    "storage",
    "<all_urls>"
  ],
  "browser_specific_settings": {
    "gecko": {
      "id": "{GUID_HERE}"
    }
  }
}
```

### Error log output 

```
WebExtError: installTemporaryAddon: Error: Error: undefined passed where a value is required
    at RemoteFirefox.installTemporaryAddon (file:///home/my_user/.nvm/versions/node/v16.13.1/lib/node_modules/web-ext/lib/firefox/remote.js:100:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FirefoxAndroidExtensionRunner.rdpInstallExtensions (file:///home/my_user/.nvm/versions/node/v16.13.1/lib/node_modules/web-ext/lib/extension-runners/firefox-android.js:506:23)
    at async FirefoxAndroidExtensionRunner.run (file:///home/my_user/.nvm/versions/node/v16.13.1/lib/node_modules/web-ext/lib/extension-runners/firefox-android.js:87:5)
    at async Promise.all (index 0)
    at async MultiExtensionRunner.run (file:///home/my_user/.nvm/versions/node/v16.13.1/lib/node_modules/web-ext/lib/extension-runners/index.js:72:5)
    at async run (file:///home/my_user/.nvm/versions/node/v16.13.1/lib/node_modules/web-ext/lib/cmd/run.js:180:3)
    at async Program.execute (file:///home/my_user/.nvm/versions/node/v16.13.1/lib/node_modules/web-ext/lib/program.js:289:7)
    at async file:///home/my_user/.nvm/versions/node/v16.13.1/lib/node_modules/web-ext/bin/web-ext.js:13:1
```

**Comment by Rob--W** [comment] 2022-09-08 09:18
Duplicate of #2499.

Update Nightly and it should work again.

**Closed** 2022-09-08 09:19 UTC
Labels: state: duplicate
