### ISSUE TITLE
Environment variables are parsed as unknown arguments

### ISSUE THREAD

**Issue by Vinnl** [mozilla/web-ext#1557] opened 2019-03-13 15:26 UTC
### Is this a feature request or a bug?

Bug

### What is the current behavior?

When you have an environment variable set (e.g. `$WEB_EXT_API_KEY`), that gets converted to a command line parameter. When that parameter is unknown, an errors is thrown.

### What is the expected or desired behavior?

No error to be thrown, potentially the current error being shown as a warning.

Relevant use case: I have set `$WEB_EXT_API_KEY` in CI to run `web-ext sign`. However, in the same environment, I run `web-ext build` - this currently fails because that is not an expected argument for it.

### Version information (for bug reports)

````
node --version && npm --version && web-ext --version
````

This is using `web-ext` 3.0.0 using Node 10. (It's in CI, so running the above command was a bit too much of a hassle.)

**Comment by Rob--W** [comment] 2019-03-13 15:45
Thanks for your report. It's a duplicate of #793 .

**Closed by Rob--W** 2019-03-13 15:45 UTC
