### ISSUE TITLE
Specifying a profile name no longer works on Mac OS X

### ISSUE THREAD

**Issue by autonome** [mozilla/web-ext#1694] opened 2019-09-02 22:31 UTC
### Is this a feature request or a bug?

Bug

### What is the current behavior?

web-ext run -f /Applications/Firefox\ Nightly.app/Contents/MacOS/firefox -p ProfileName

Results in this error:

> Temporary add-on installation is not supported in this version of Firefox (you need Firefox 49 or higher). For older Firefox versions, use --pre-install
    at c.startFirefoxInstance (/Users/dietrich/.npm-packages/lib/node_modules/web-ext/dist/webpack:/src/extension-runners/firefox-desktop.js:278:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

### What is the expected or desired behavior?

Nightly starts with the specific profile.

### Version information (for bug reports)

* **Firefox version**:
* **Your OS and version**:
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````

v10.15.0
6.11.2
3.1.1

**Comment by autonome** [comment] 2019-09-02 22:38
tried with --firefox-profile-path and get the same error

**Comment by Rob--W** [comment] 2019-09-03 08:46
Duplicate of #1692. Already fixed on Nightly - https://bugzilla.mozilla.org/show_bug.cgi?id=1578108

**Closed by Rob--W** 2019-09-03 08:46 UTC
