### ISSUE TITLE
Proposal to add a new command to generate boilerplate code for an extension

### ISSUE THREAD

**Issue by ankushduacodes** [mozilla/web-ext#2127] opened 2021-01-19 04:04 UTC
### Is this a feature request or a bug?
Feature request / Feature proposal

### Description
I would like to propose a new command something like `web-ext new` which will generate a boilerplate code for an extension with some basic files like `manifest.json`, `background.js` etc and equally importantly a `README` file that will include some basic description of generated files and some important links to documentation.

We can also consider adding a command-line survey that may ask users if this is their first time building extension and if that is the case we can generate the boilerplate extension with no further questions AND if that is not the case then we can ask more questions as to what files they do want to be in the dir and what they don't want to be there.

**Comment by Rob--W** [comment] 2021-01-19 12:12
Duplicate of #540 ?

**Comment by rpl** [comment] 2021-01-19 12:37
> Duplicate of #540 ?

it is indeed a duplicate of that pre-existing issue.

@ankushduacodes look to https://github.com/mozilla/web-ext/issues/540#issuecomment-762814028 for some details about how to use the [create-webextension](https://www.npmjs.com/package/create-webextension) npm package that I created some (long :-P) time ago.

**Closed by rpl** 2021-01-19 12:37 UTC
Labels: state: duplicate
