### ISSUE TITLE
Reload not deleting previous background page/script

### ISSUE THREAD

**Issue by Anon1987** [mozilla/web-ext#824] opened 2017-02-28 00:38 UTC
### Is this a bug or feature request?
Bug

### What is the current behavior?
Using web-ext reload and listener on the background page/script. Older background pages seems to be still active and able to listen for event. More precisely, a popup window is opened for each background page alive (i.e. each reload)

#### Step to reproduce
```
// background script .js
function api_rcv(message, sender, sendResponse){
    browser.windows.create({'url': 'https://github.com', 'type': 'popup', 'width':300, 'height':300})
}
browser.runtime.onMessage.addListener(api_rcv)
```
```
// content_script.js
browser.runtime.sendMessage({'open_popup'})
```
Reload the script by modifying it, and then call the content_script function again. Two popup should appear. 

### What is the expected or desired behavior?
When the extension reloads, the previous background page and attached script should be destroyed.

### Version information (for bug reports)

* **Firefox version**: 51.0.1 (64 bits)
* **Your OS and version**: macOS 10.12.1 (16B2657)
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version

v6.0.0
3.8.6
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kcorre/.nvm/versions/node/v6.0.0/lib/node_modules/web-ext/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kcorre/.nvm/versions/node/v6.0.0/lib/node_modules/web-ext/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kcorre/.nvm/versions/node/v6.0.0/lib/node_modules/web-ext/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3) code: 'MODULE_NOT_FOUND' }
1.8.1
````

**Comment by kumar303** [comment] 2017-03-01 22:23
Thanks for the report. Could you try reproducing it without web-ext, by [loading it as a temporary add-on](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Temporary_Installation_in_Firefox) and pressing the Reload button on the `about:debugging` page?

Also, your dtrace warnings might be because you are executing a different version of Node than what you installed `web-ext` with. Reinstalling `web-ext` like this might fix it: `npm uninstall -g web-ext && npm install -g web-ext`.

**Comment by kumar303** [comment] 2017-03-02 20:49
Actually, this sounds like https://bugzilla.mozilla.org/show_bug.cgi?id=1273251 so I think your issue may be fixed in a newer Firefox. The patch landed in Firefox 53 so can you try again with `web-ext run --firefox=nightly` or `--firefox=firefoxdeveloperedition`?

This bug may also be related: https://bugzilla.mozilla.org/show_bug.cgi?id=1272758

**Comment by Sparika** [comment] 2017-03-03 10:01
Thank you for your answers. 

Reloading any page kind of solve the issue. Scripts seems to be still alive, but after a page reload, only the last extension receives the sendMessage. 

Nightly 54 seems to solve the issue.

**Comment by kumar303** [comment] 2017-03-03 15:29
Thanks for confirming. Since this is fixed in Firefox 54, I'll close the bug. There's no workaround that I can think of for older versions of Firefox.

**Closed by kumar303** 2017-03-03 15:29 UTC
