### ISSUE TITLE
High CPU usage with nothing opened

### ISSUE THREAD

**Issue by Juraj-Masiar** [mozilla/web-ext#2219] opened 2021-04-12 17:06 UTC
### Is this a feature request or a bug?
Bug

### What is the current behavior?

For the past few weeks I'm experiencing a very annoying bug that usually appears few minutes / hours after starting Firefox (using web-ext).
I have no steps to reproduce but it's happening almost every day and I don't believe it's just me.
The problem looks like an infinite loop or something running extensively in a thread taking 12% out of my 12 thread CPU.
The command line shows some info but I'm not sure it helps:

![image](https://user-images.githubusercontent.com/6358971/114432078-93c32d00-9bc0-11eb-877b-476d0f431c26.png)

Due to the current CPU architecture, high single thread load will cause high frequency boost => high TDP => high fan speed :(.

### Version information (for bug reports)

* **Firefox version**: 88.0b9 
* **Your OS and version**:  Win 20H2

````
v14.0.0
6.14.11
6.0.0
````

EDIT:
I've checked "about:performance" but there is nothing with elevated energy impact or memory usage.
I've also tried to free the memory from the "about:memory" page but again with no change.

**Comment by rpl** [comment] 2021-04-13 12:52
@Juraj-Masiar the only things in web-ext that may be related to this (at least the one that I can think of at the moment) are:
- the extension is being reloaded more often than expected (e.g. if something in the extension build system is updating a file that web-ext is watching and triggers many addon reloads)
- some issue on the Firefox side due to some prefs that web-ext sets by default in the profile it does create to test the target extension

If the issue turned out to be the first one mentioned in the above list, a solution may be to tell web-ext to watch only some specific files (using `--watch-file` cli option) or to make the web-ext watcher to ignore some files (using `--watch-ignored`).

If the issue turned out to be on the Firefox side (which is actually more likely), then I would suggest to report it on bugzilla, where it belongs. 

To prepare a more detailed bug report (and increase the changes to have it investigated) it may be a good idea to:
- use the web-ext options to persist the profile and be able to use it without web-ext (e.g. by combining `--firefox-profile` and `--keep-profile-changes` cli options) to be sure that the bug can be reproduced without web-ext in the STR.
- retrieve about:support info to attach in the bug
- look in the browser console while the high cpu usage is being reporduced, in case there is some visible log spam that may help investigating the issue
- try to collect a profile using the perf-html.io tool, because it may show us what is keeping the Firefox processes busy (for some "high cpi usage" issues that may not always possible, e.g. because collecting the profile may make the cpu usage even worse and prevent the profile data to be successfully collected and reported to perf-html.io, but it is worth a try)

I'm not closing this issue yet, but it is technically incomplete as it is, and very likely invalid from a web-ext perspective, because there is very likely that the issue isn't something that would have to be fixed on the web-ext side.

**Comment by Juraj-Masiar** [comment] 2021-04-13 21:35
Thanks for the info!
I will investigate it further. I can't believe nobody else reported this yet as this happens even on a completely blank profile with a single small extension (but not always).
It's not a build system related - I've noticed it starts even when I'm not doing anything, like there is a scheduled task that fails to finish. 
It doesn't happen in my normal Firefox nor Nightly, only in instances started with web-ext. And it's frustrating when I see the problem but I can't investigate it...

**Comment by rpl** [comment] 2021-04-15 11:58
> Thanks for the info!
> I will investigate it further. I can't believe nobody else reported this yet as this happens even on a completely blank profile with a single small extension (but not always).
> ...
> It doesn't happen in my normal Firefox nor Nightly, only in instances started with web-ext. And it's frustrating when I see the problem but I can't investigate it...

well, if you can reproduce it consistently enough with a single small extension, then that may allow you to get to an STR that may make it possible to investigate the issue with the less amount of unrelated noise possible.

Over the time we got reports related to high CPI usage, in a good amount of  cases there was something on the extension side that was triggering the issue and it has been fixed on the extension side (while in other case we determined that there was an issue on the Firefox side to fix). 

As a side note, in some cases the extension may be just doing something that is more "passive" (like listening for certain WebExtensions API events) than "active" (like calling some specific WebExtension API methods) to trigger this kind of issues.

As an example if a single extension is intercepting web requests, Firefox will be forwarding (over IPC) webRequest events for all top level and sub resources requests that are matching what the extension can and wants to see, and that may keep the process busy even if the extensions isn't really doing anything with the events received.

Collecting a profile using perf-html.io while you are reproducing the issue may shade some lights on what the Firefox processes are busy doing and allow us to investigate it further.

I'm going to close this issue (as incomplete), because as it is right now we don't have enough details to be sure that web-ext does have an actual role in the cpu usage, and based on the current details available I would say that the preferences set by web-ext are the only thing that seems it may be related, this is still looking more like a Firefox bug than a web-ext one.

Feel free to mention me in this issue if you got any new details that may be useful to investigate this, or if you filed a bug in bugzilla to continue the investigation.

**Closed by rpl** 2021-04-15 11:58 UTC
Labels: state: incomplete

**Comment by Juraj-Masiar** [comment] 2021-04-18 10:16
So this is what I found out:
- the browser console is empty
- nothing suspicious in the web-ext --verbose log either
- the bug continues after closing web-ext and my webpack build console
- the bug continues after removing the extension (so there are no extensions at all)
- I would like to mention this happens (from time to time) during development on all of my extensions, even those extremely simple once that has only `"storage"` permission.
- the "about:processes" shows 100% CPU for the Extensions
![Screenshot 2021-04-18 12 13 59](https://user-images.githubusercontent.com/6358971/115142016-b382a700-a03f-11eb-8054-a2f24eceb519.png)

I've also made a copy of the temp profile while it was running, but re-executing it in a new Firefox instance didn't make the bug reappear.

The Profiler supports different settings so I've executed it with each one for about 2 seconds:
https://share.firefox.dev/3x2wZZf
https://share.firefox.dev/3ebdWDB
https://share.firefox.dev/3x5gDze
https://share.firefox.dev/3go09fs
https://share.firefox.dev/3snfr6E

But I can't read it, can you see something there @rpl ?
Is this gonna be enough for the bugzilla report? I mean, I really don't want to waste someones time, I feel bad already for my original post not having enough data in it :(.

**Comment by rpl** [comment] 2021-04-20 18:01
@Juraj-Masiar I looked to the profiles linked but they don't seem to contain enough to make me see precisely enough what is keeping the process busy (but I do see that there is a visible jank that is delaying the event processing, which definitely hints that there is something that was keeping that process quite busy, and that we are piping some data between processes, which may be related to the jank but I wasn't able to see enough details to figure out what is exactly triggering that).

Some other Firefox engineers may be able to spot  in these profiles some other details that I wasn't able to spot based on my quick look, but if we could get a profile with some more data we may increase the chances to have enough to investigate it as part of a bugzilla issue.

Could you try to collect one a bit longer than 2 seconds? or is the process so busy that the entire browser get stuck if you try that? 

(I recall that I investigated at least one Firefox bug for which I had to stop the profiler quick enough to be able to collect it successfully and so I don't exclude that was the reasons why all these profiles were ~2 seconds long)

Also, would you mind to briefly describe me some of the other details of your steps to reproduce? e.g.
- could you link me the sources of the minimal web extension that is triggering the issue for you? 
  (e.g. I would like to double-check if there is a possible correlation with subscribing some webextensions API events or something like that, or a content script accessing some DOM properties on an attached windows)
- was there any tab loaded or loading? any specific urls?

Thanks in advance for your help investigating this Firefox issue.

**Comment by Juraj-Masiar** [comment] 2021-04-21 13:58
I'm trying to find some pattern here, but it's crazy random.
Today I've started working at 9:30 and the bug appeared just now at 15:20. So that's a 6 hours it took the bug to present itself. Also my build console (webpack) was not even running.

When this happens, the extension is perfectly OK, it's fast, no signs of any delays. Actually whole Firefox runs just fine. I can check for updates, check for addon updates, switch theme, change settings, visit sites... everything works perfectly normal (apart from CPU running crazy).
I had only few tabs opened - addon page, about:debugging, background page debugger. Also I was not interacting with it when it happened. It feels like it always happens when I'm not using it. But at the same time I was out for a walk today for one hour and when I came back, everything was still fine. My PC didn't went to sleep, it's set for several hours.
I'm able to reproduce the problem sometimes simply by executing few instances of the web-ext and without any further interaction!

I've made the recording short on purpose to have a small batch of data (thinking it would be easier to spot the issue).
This is a much longer recording, it's Firefox instance with a single "about:blank" tab opened and with 0 extensions (apart from some build in).
https://share.firefox.dev/3x7nOa5

I will try to reproduce it with some small extension that I can share...

**Comment by Tynach** [comment] 2021-07-14 01:36
I'm seeing exactly this on standard Firefox 89.0.2 on Ubuntu 20.04. The only strange thing I do related to extensions is install one extension that is loaded from a folder, as it's a modified version of a Chrome extension that I just kinda use occasionally to simulate color blindness. Just slaps a div in front of a page, makes it so mouse clicks don't intercept it, and adds an SVG-specified filter. Also dumps the contents of the SVG file to the end of the page, though the SVG file only contains filter definitions and nothing else.

Technically I'm on KDE Neon, actually, but the repositories I got Firefox from are the Ubuntu 20.04 repositories.

**Comment by Dook1** [comment] 2021-07-15 18:28
https://bugzilla.mozilla.org/show_bug.cgi?id=1706594
