### ISSUE TITLE
Required login to fill an anonymous survey?

### ISSUE THREAD

**Issue by DamienCassou** [mozilla/web-ext#1063] opened 2017-08-26 18:28 UTC
There is currently a survey regarding the roadmap of web-ext. This survey is hosted by Google which already annoys me because of the power Google already has. Beyond that, the survey requires logging in on google.com:

> Sign in to your Google account to fill out this form

Why is that so?? What is the relationship between my google account and this "anonymous" survey?

I don't want to answer the survey in these conditions.

**Comment by kumar303** [comment] 2017-08-28 17:23
Hmm, I don't know why the form requires a Google sign-in. @andymckay can we lift that requirement?

I tested this in a private tab and I can confirm that it does require sign-in: https://click.e.mozilla.org/?qs=50f20c4c404d90879caea433b1a0f1cea8c9210ae3c037cbab6228bbd2f36b9e66db634c24c0ebec70b18b54863cddcda880b55b2e160515

**Comment by andymckay** [comment] 2017-08-28 17:43
Oh oops, because I had the "limit to 1 response" button checked. Sorry about that, should be fixed.

ps: Kumar you have full admin rights on the survey :)

**Closed by andymckay** 2017-08-28 17:43 UTC

**Comment by kumar303** [comment] 2017-08-28 18:19
thanks for the bug report, @DamienCassou
