### ISSUE TITLE
Error: Your connection is not secure

### ISSUE THREAD

**Issue by pixelass** [mozilla/web-ext#374] opened 2016-07-17 09:01 UTC
I keep getting the following Error:

<img width="1068" alt="screen shot 2016-07-17 at 11 00 28 am" src="https://cloud.githubusercontent.com/assets/1148334/16899687/9b713874-4c0d-11e6-8d20-ca69773384da.png">
 when running

`web-ext run --firefox-binary=/Applications/FirefoxNightly.app/Contents/MacOS/firefox-bin`
or
`web-ext run --pre-install`

advice appreciated

**Comment by kumar303** [comment] 2016-07-18 15:43
Hi.
I tested `web-ext run` with today's Nightly and I don't see any errors when connecting to https://www.youtube.com. Are there any additional steps to reproduce this error? Does it happen when you run all extensions? Does it happen in other browsers when not using `web-ext run`?

It is possible, of course, to build an extension that attempts to proxy requests -- i.e. your extension may be causing this. 

It is also possible that some profile settings introduced by `web-ext run` is somehow causing this. When you start a browser with `web-ext run` you could visit `about:support` and that will show a link to the `user.js` file which has all of `web-ext`'s custom preferences.

**Comment by pixelass** [comment] 2016-07-18 16:41
i cannot open any pages. same error on all urls

On Jul 18, 2016 17:43, "Kumar McMillan" <notifications@github.com> wrote:
>
> Hi.
> I tested web-ext run with today's Nightly and I don't see any errors when
connecting to https://www.youtube.com. Are there any additional steps to
reproduce this error? Does it happen when you run all extensions? Does it
happen in other browsers when not using web-ext run?
>
> It is possible, of course, to build an extension that attempts to proxy
requests -- i.e. your extension may be causing this.
>
> It is also possible that some profile settings introduced by web-ext run
is somehow causing this. When you start a browser with web-ext run you
could visit about:support and that will show a link to the user.js file
which has all of web-ext's custom preferences.

**Comment by kumar303** [comment] 2016-07-18 16:43
> i cannot open any pages. same error on all urls

Does it only happen when using `web-ext run`? Or does it happen during normal browsing in Firefox or other browsers?

**Comment by pixelass** [comment] 2016-07-18 16:51
only with web-ext  .. I'll test an empty extension when I get home

**Comment by kumar303** [comment] 2016-07-18 16:59
You could also try disabling the extension on `about:addons` to see if the error goes away or not

**Comment by pixelass** [comment] 2016-07-18 21:09
No success. I disabled it, then removed it.

Opened a bunch of random pages from (wikipedia, twitter, google ...) which all have the same error.  

All mozilla pages work though. Only `https` is affected (obviously)

<img width="1279" alt="screen shot 2016-07-18 at 11 08 06 pm" src="https://cloud.githubusercontent.com/assets/1148334/16930453/9378ae88-4d3c-11e6-81a4-f49e2512bf44.png">

**Comment by pixelass** [comment] 2016-07-18 21:13
```
user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("browser.download.manager.showWhenStarting", false);
user_pref("browser.EULA.override", true);
user_pref("browser.EULA.3.accepted", true);
user_pref("browser.link.open_external", 2);
user_pref("browser.link.open_newwindow", 2);
user_pref("browser.offline", false);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.search.update", false);
user_pref("extensions.blocklist.enabled", false);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnOpen", false);
user_pref("browser.startup.page", 0);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("startup.homepage_welcome_url", "about:blank");
user_pref("devtools.errorconsole.enabled", true);
user_pref("dom.disable_open_during_load", false);
user_pref("extensions.autoDisableScopes", 10);
user_pref("extensions.logging.enabled", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("network.manage-offline-status", false);
user_pref("network.http.max-connections-per-server", 10);
user_pref("network.http.phishy-userpass-length", 255);
user_pref("offline-apps.allow_by_default", true);
user_pref("prompts.tab_modal.enabled", false);
user_pref("security.fileuri.origin_policy", 3);
user_pref("security.fileuri.strict_origin_policy", false);
user_pref("security.warn_entering_secure", false);
user_pref("security.warn_entering_secure.show_once", false);
user_pref("security.warn_entering_weak", false);
user_pref("security.warn_entering_weak.show_once", false);
user_pref("security.warn_leaving_secure", false);
user_pref("security.warn_leaving_secure.show_once", false);
user_pref("security.warn_submit_insecure", false);
user_pref("security.warn_viewing_mixed", false);
user_pref("security.warn_viewing_mixed.show_once", false);
user_pref("signon.rememberSignons", false);
user_pref("toolkit.networkmanager.disable", true);
user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.prompted", 2);
user_pref("toolkit.telemetry.rejected", true);
user_pref("javascript.options.showInConsole", true);
user_pref("browser.dom.window.dump.enabled", true);
user_pref("webdriver_accept_untrusted_certs", true);
user_pref("webdriver_enable_native_events", true);
user_pref("webdriver_assume_untrusted_issuer", true);
user_pref("dom.max_script_run_time", 30);
user_pref("javascript.options.strict", true);
user_pref("devtools.debugger.remote-enabled", true);
user_pref("devtools.debugger.prompt-connection", false);
user_pref("extensions.checkCompatibility.nightly", false);
user_pref("extensions.enabledScopes", 5);
user_pref("extensions.getAddons.cache.enabled", false);
user_pref("extensions.installDistroAddons", false);
user_pref("extensions.update.url", "http://localhost/extensions-dummy/updateURL");
user_pref("extensions.blocklist.url", "http://localhost/extensions-dummy/blocklistURL");
user_pref("extensions.webservice.discoverURL", "http://localhost/extensions-dummy/discoveryURL");
user_pref("xpinstall.signatures.required", false);
user_pref("browser.startup.homepage", "about:blank");
user_pref("startup.homepage_welcome_url.additional", "");
user_pref("devtools.chrome.enabled", true);
user_pref("urlclassifier.updateinterval", 172800);
user_pref("browser.safebrowsing.provider.0.gethashURL", "http://localhost/safebrowsing-dummy/gethash");
user_pref("browser.safebrowsing.provider.0.keyURL", "http://localhost/safebrowsing-dummy/newkey");
user_pref("browser.safebrowsing.provider.0.updateURL", "http://localhost/safebrowsing-dummy/update");
```

**Comment by kumar303** [comment] 2016-07-18 21:47
Does it still happen when you do `web-ext run` on another extension? You could try one of these examples: https://github.com/mdn/webextensions-examples/

**Comment by pixelass** [comment] 2016-07-18 21:56
same issue

**Comment by kumar303** [comment] 2016-07-18 21:59
OK, so it's not an issue with your extension. The next thing would be to try `web-ext run` in some different versions of Firefox. If you have Firefox Developer Edition and it's up to date, try `web-ext run` there. Also, check that your Nightly is up to date. What platform are you on? Mac, Linux, Windows?

**Comment by kumar303** [comment] 2016-07-18 22:01
What is your exact `web-ext run` command? Are you using `--firefox-profile` to copy an existing profile? If so, try without that option.

**Comment by pixelass** [comment] 2016-07-18 22:01
I tired developer edition via `web-ext run --pre-install`  as mentioned in the first comment

My nightly is up to date and was downloaded especially for this use case, so it's totally vanilla.

Using OS X

**Comment by pixelass** [comment] 2016-07-18 22:07
My bad..  `--pre-install` used my default FF.. I was able to run the examples and my extension with DeveloperFF now. When I use the default FF the SSL issue also occurs

**Comment by kumar303** [comment] 2016-07-18 22:22
Do you have anti-virus software? If so, try disabling SSL temporarily just to see if it makes the error go away. I saw another bug report that suggests when you first install an application, sometimes the anti-virus software doesn't register it correctly. To see if that's the issue, you can uninstall Nightly and re-install it again (just delete `FirefoxNightly.app`, re-download the installer).

**Comment by pixelass** [comment] 2016-07-18 22:36
good catch. I use a paid version of [Adguard](https://adguard.com/en/welcome.html) which is installed on my computer. Disabling it fixes the issue

**Comment by pixelass** [comment] 2016-07-19 12:01
Not sure how to proceed here. Do you want me to open a new issue or can we just keep this one?

**Comment by kumar303** [comment] 2016-07-19 14:53
Great, glad we figured it out. This would not be directly related to `web-ext` so I'll close the issue. If you want to turn Adguard back on, this may help you fix it https://malwaretips.com/threads/firefox-your-connection-is-not-secure.57032/ I think the reason it works in non-Firefox browsers is because Firefox is more strict about trusting root certificates. I'm not sure how it worked in Dev Edition though. I think you can rectify the problem by adding the Adguard root certificate to Firefox but I'm not sure. The link above says you can try disabling and re-enabling.

**Closed by kumar303** 2016-07-19 14:53 UTC

**Comment by pixelass** [comment] 2016-07-19 15:21
It works in Firefox Developer mode with Adguard on. Therefore it is not consistent between different versions of Firefox thus I see it as an issue. 
Obviously this is just my suggestion.

<img width="1102" alt="screen shot 2016-07-19 at 5 22 21 pm" src="https://cloud.githubusercontent.com/assets/1148334/16955525/378289d4-4dd5-11e6-8478-2f5412375d38.png">

**Comment by andymckay** [comment] 2016-07-19 15:54
But it's not an issue with web-ext, so I agree with kumar on closing. You might need to take it up with Adguard or Firefox.

**Comment by pixelass** [comment] 2016-07-19 16:00
It only happens when I run the browsers with `web-ext`. The issue does not occur when I start the browsers without `web-ext`.

I'm fine with closing this issue. I know how I can work-around now and it does not cause issues with my process.
