### ISSUE TITLE
Sign command exits with zero status when signing fails

### ISSUE THREAD

**Issue by robertknight** [mozilla/web-ext#585] opened 2016-10-17 01:17 UTC
### Is this a bug or feature request?

Bug

### What is the current behavior?

1. Run `web-ext sign` to sign an add-on with version X
2. Run `web-ext sign` again with the same version in the manifest. Signing will fail and the command will print "FAIL" as the last output
3. Check the exit status of the `web-ext sign` command (eg. via `echo $?` in bash). See that it is zero.

### What is the expected or desired behavior?

When signing fails, the command should exit with a non-zero status, so that `make` or a deployment shell script can react accordingly.

### Version information

(Please fill this in for bug reports.)

web-ext 1.5.0
node v6.8.1
Ubuntu 16.04

**Comment by kumar303** [comment] 2016-10-17 02:05
Oof, good catch and thanks for filing a bug. I can reproduce it.

**Comment by kumar303** [comment] 2016-10-17 02:14
I'm nominating this as a good first bug because I think it can be fixed with the following changes:
* Introduce a new `signCommand()` function which will be a wrapper for `sign()` (to still support programmatic use). 
* Make `web-ext sign` call this new `signCommand()` method instead of `sign()`.
* Make `signCommand()` raise a `UsageError` when `sign()` resolves with `{success: false}`

Here is info on how to manually test the `sign` command: https://github.com/mozilla/web-ext/blob/master/CONTRIBUTING.md#working-on-web-ext-sign

**Comment by shubheksha** [comment] 2016-10-17 12:48
I'll work on this!

**Closed** 2016-10-17 15:36 UTC
Labels: bug, maybe good first bug

**Comment by kumar303** [comment] 2016-10-17 15:37
Thanks @shubheksha !

@robertknight this is fixed on master and we will release it shortly

**Comment by robertknight** [comment] 2016-10-17 16:32
Great! - Thanks for the quick resolution.
