### ISSUE TITLE
Unknown argument: firefox

### ISSUE THREAD

**Issue by Saphareas** [mozilla/web-ext#1399] opened 2018-11-22 16:00 UTC
### Is this a feature request or a bug?
It's a bug (I think).

### What is the current behavior?
I've set the path to my Firefox using the `WEB_EXT_FIREFOX` environment variable.
Now when running `web-ext build` it just prints the help followed by `Unknown argument: firefox`

### What is the expected or desired behavior?
`web-ext build` should just ignore the argument and run.

### Version information (for bug reports)
* **Firefox version**: 64.0b11 (64-Bit) Dev Edition
* **Your OS and version**: Kubuntu 18.10
* **Node version**: v8.11.4
* **npm version**: 6.4.1
* **web-ext version**: 2.9.1

**Comment by Rob--W** [comment] 2018-11-23 10:16
This seems like a duplicate of #793.

As a work-around, you could use a `.web-ext-config.js` file, see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Getting_started_with_web-ext#Setting_option_defaults_in_a_configuration_file and https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Getting_started_with_web-ext#Automatic_discovery_of_configuration_files

**Closed by Rob--W** 2018-11-23 10:16 UTC
