### ISSUE TITLE
`web-ext sign` does not support reading config files

### ISSUE THREAD

**Issue by mantou132** [mozilla/web-ext#1816] opened 2020-01-11 12:19 UTC
### Is this a feature request or a bug?
A bug in my opinion

### What is the current behavior?
```
web-ext --config web-ext.config.js sign
```
error:
```
Missing required arguments: api-key, api-secret
```

### What is the expected or desired behavior?
Read `api-key`, `api-secret` in configuration file

### Version information (for bug reports)

* **Firefox version**: 74
* **Your OS and version**: MacOS 10.14
* Paste the output of these commands:

````
$ node --version && npm --version && npx web-ext --version
v13.5.0
6.13.4
4.0.0
````

**Comment by Rob--W** [comment] 2020-01-11 14:47
Duplicate of #1327

**Closed by Rob--W** 2020-01-11 14:47 UTC
