### ISSUE TITLE
Quiet `sign` progress bar

### ISSUE THREAD

**Issue by t-mart** [mozilla/web-ext#2429] opened 2022-06-09 21:50 UTC
### Is this a feature request or a bug?

Feature request

### What is the current behavior?

I'm using web-ext programmatically inside a build script. I'm calling `sign` like this:

```typescript
import webExt from "web-ext";

await webExt.cmd.sign({
  apiKey,
  apiSecret,
  verbose: false,  // this doesn't seem to help
  channel: "unlisted",
});
```

Running this build script from an interactive terminal is fine: A progress bar is "animates".

But, **when the output stream is not an interactive terminal** (but instead something like a log file on a CI runner), this renders usually several thousands of lines of:

```
...
Signing add-on [ .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . ]
Signing add-on [  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .]
Signing add-on [.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  ]
Signing add-on [ .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . ]
Signing add-on [  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .]
Signing add-on [.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  ]
Signing add-on [ .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . ]
Signing add-on [  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .]
Signing add-on [.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  ]
Signing add-on [ .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . ]
Signing add-on [  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .]
Signing add-on [.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  ]
...
```

Looking at some sample log files, there appear to be about **20 lines/progress-bar-updates per second**.

### What is the expected or desired behavior?

The progress bar should be toggle-able with some kind of option.

From what I can tell, this output actually comes from <https://github.com/mozilla/sign-addon>. Recently, that project implemented [Made progress bar optional in Client](https://github.com/mozilla/sign-addon/pull/826), which provides the `disableProgressBar` option. See <https://github.com/mozilla/sign-addon/blob/master/src/index.js#L62>

However, web-ext is the glue to sign-addon, and does not pass through the `disableProgressBar`  option. See <https://github.com/mozilla/web-ext/blob/master/src/cmd/sign.js#L114>, where only a subset of the sign-addon options are passed.

There seem to be a few ways this could be fixed, but at the very least, `disableProgressBar` should a recognized and passed-through option to `webExt.cmd.sign`.

### Version information (for bug reports)

* **Firefox version**: `101.0`
* **Your OS and version**: `Windows 10`
* **Node**: `v18.3.0`
* **npm**: `8.11.0`
* **web-ext**: `6.8.0`

**Comment by rpl** [comment] 2022-06-10 18:15
Hi @t-mart,
This is a duplicate of #2154.

We added that option to sign-addon some time ago to make it simpler to address the web-ext issue #2154.

The following comment provides a brief summary of the proposed approach: https://github.com/mozilla/web-ext/issues/2154#issuecomment-953185284

**Closed by rpl** 2022-06-10 18:15 UTC
Labels: state: duplicate
