### ISSUE TITLE
Allow multiple --source-dir parameters in run to load multiple temporary extensions

### ISSUE THREAD

**Issue by davidmaxwaterman** [mozilla/web-ext#2599] opened 2023-01-07 11:23 UTC
### Is this a feature request or a bug?
Feature, but a bit of both.

### What is the current behavior?
It will only handle one --source-dir parameter.

### What is the expected or desired behavior?
I would like to be able to specify multiple --source-dir parameters so it will load multiple temporary extensions.

Perusing the code, I see that the library used can handle multiple extensions, so it seems like the restriction is entirely in the command line processing.

My use-case is that I am developing an extension, and I need to use a testing tool that works on a regular web page, so I need another extension to allow me to serve as middleware...in my case, it is simulating the user manipulating bookmarks. My middleware extension allows the test harness access to the bookmarks API.

So, I effectively want to do something like this:

```
web-ext --source-dir extension-under-test/dist/ --source-dir bookmarks-middleware/dist/ test-harness/test/index.html
```

### Version information (for bug reports)

- **Firefox version**:n/a (but 110.0a1)
- **Your OS and version**:OSX 13.1
- Paste the output of these commands:

```
node --version && npm --version && web-ext --version
v16.15.0
8.14.0
7.3.1
```

**Comment by Rob--W** [comment] 2023-01-07 17:55
Duplicate of #1107.

**Closed by Rob--W** 2023-01-07 17:55 UTC
Labels: state: duplicate
