### ISSUE TITLE
Preinstall add-ons during web-ext run?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/web-ext#1393] opened 2018-11-05 19:58 UTC
### Is this a feature request or a bug?
Feature request.

### What is the current behavior?

I'm trying to test a Pioneer study which requires me to preinstall the https://addons.mozilla.org/en-US/firefox/addon/firefox-pioneer/ add-on and set a config in about:config. I like the <kbd>$ web-ext run</kbd> behavior of a empty profile, but it'd be nice if I could specify 1+ add-ons that should be preinstalled using my web-ext-config.js file, similar to how I can specify a `startUrl` and `pref` array for my custom about:config preferences:

```js
    startUrl: ["about:debugging"],
    pref: ["shieldStudy.logLevel=All"],
```

### What is the expected or desired behavior?

Maybe an array of add-ons which will be preinstalled with each new <kbd>$ web-ext run</kbd> command and temporary profile. That way maybe I can specify something like this:

```js
    addons: ["firefox-pioneer"],
```

And it will preinstall https://addons.mozilla.org/en-US/firefox/addon/firefox-pioneer/ for me before loading the current add-on.

### Version information (for bug reports)

* **Firefox version**:
* **Your OS and version**:
* Paste the output of these commands:

```sh
$ node --version && npm --version && $(npm bin)/web-ext --version

v10.10.0
6.4.1
2.9.1
```

**Comment by rpl** [comment] 2018-12-20 14:19
@pdehaan I'm not that kin to include a "auto-download an addon by id" as an integrated web-ext feature, but part of the web-ext internals already support more than one "extension source dir" to be used in a "web-ext run" command, but it is not yet exposed by the command line options.

Once we add the support for more than one "extension source dir" in the "web-ext run" command  (tracked by #1107), it should be much easier to support this use case even without "auto-downloading an addon by id" as an integrated feature (e.g. a nodejs script in the extension project could ensure that the other extension is available locally and download it if it is not, and then execute "web-ext run" by passing both the extensions).

And so I'm closing this as a duplicate of #1107 and including #1107 into the feature we want in the next web-ext 3.0.0 version.

**Closed by rpl** 2018-12-20 14:19 UTC
Labels: state: duplicate
