### ISSUE TITLE
Support source code submission

### ISSUE THREAD

**Issue by yan12125** [mozilla/web-ext#1624] opened 2019-06-01 13:41 UTC
### Is this a feature request or a bug?
Feature request

### What is the current behavior?
Firefox will requre source code submission for obfuscated/transpiled/minimized/... addons since June 10th, 2019 [1]. Currently I have to go to addons.mozilla.org in browsers and submit source code tarballs.

[1] https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/AMO/Policy/Reviews-2019-05#Source_Code_Submission

### What is the expected or desired behavior?
web-ext can do that for me

**Comment by rpl** [comment] 2019-07-04 13:44
In #804 we were discussing about a separate `web-ext submit` command to also submit addon metadata and source code tarballs, and so I'm closing this a duplicate of #804.

**Closed by rpl** 2019-07-04 13:44 UTC
Labels: state: duplicate
