### ISSUE TITLE
ENOENT error when I try to build or test on "from source" installation

### ISSUE THREAD

**Issue by onazaro** [mozilla/web-ext#582] opened 2016-10-16 14:01 UTC
### Is this a bug or feature request?
Bug

### What is the current behavior?
I'm trying to follow [Development of web-ext](https://github.com/mozilla/web-ext/blob/master/CONTRIBUTING.md) instructions.

Installation went OK.
But when I try `npm start` or `npm test`, I get this error:

`Fatal error: spawn /home/pal/web-ext/node_modules/grunt-flowbin/node_modules/flow-bin/vendor/flow ENOENT` 

### Version information

(Please fill this in for bug reports.)

* Output of `web-ext --version`: 1.5.0
* Output of `node --version`: v4.6.0
* Output of `npm --version`: 3.10.8
* Firefox version: 49.0
* Your OS and version: Ubuntu 16.04 64

**Comment by onazaro** [comment] 2016-10-16 15:23
The same on Win32

**Comment by onazaro** [comment] 2016-10-16 16:00
Sorry, not the same on Win32.

On the Ubuntu I seem to hack the issue locally by copying **/vendor**
from **web-ext/node_modules/flow-bin**
to **web-ext/node_modules/grunt-flowbin/node_modules/flow-bin**

But on Win32 it needs **flow.exe** which seem not to be there at all: according to https://github.com/facebook/flow/blob/master/README.md the Flow works only on 64-bit systems.

**Comment by onazaro** [comment] 2016-10-16 16:16
Upd.

Maybe the hack was not so good:
My Ubuntu 64 with 6GB RAM is stuck, including GUI and muse pointer, for more than 2 hours already <Running "flowbin:check" (flowbin) task>

**Comment by kumar303** [comment] 2016-10-16 20:23
@rpl do you have any ideas for what might be going on? I know we changed these install deps recently.

**Comment by shubheksha** [comment] 2016-10-17 07:31
I have faced a similar problem. The `flowbin:check` task used to hang up indefinitely before crashing. It was a memory issue most of the times. However, after a while, can't pin-point exactly when, it started working normally.

**Comment by rpl** [comment] 2016-10-17 11:46
@kumar303 it looks like we are not yet using the updated grunt-flowbin (which is version 0.1.6, while we are currently depending from the exact 0.0.6 version, and if we update grunt-flowbin dependency then flow would complain about 4 type errors, the ones fixed by  cc6d3b8 from #554)

I tried to reproduce the issue by recreating locally an environment with the same versions of Ubuntu, node and npm, but the "Fatal error: spawn ... flow NOENT" issue didn't happened to me locally and the `flowbin:check` task has been able to complete successfully.

Nevertheless, even if on my system the `node_modules/grunt-flowbin/node_modules/flow-bin/vendor/flow` binary was not missing, I tried to copy the content of `node_modules/flow-bin/vendor` to `node_modules/grunt-flowbin/node_modules/flow-bin/vendor`, to  recreate the workaround described in comment https://github.com/mozilla/web-ext/issues/582#issuecomment-254055355 and this seems to be able to recreate the issue described in #583:
the `flowbin:check` task got stuck and it looks like, by looking at the `top`, that it is spawning a huge number of instances of the node process.

On the contrary, if I copy the entire content of  `node_modules/flow-bin/` into `node_modules/grunt-flowbin/node_modules/flow-bin/`, the `flowbin:check` completes with the expected failures (related to the flowbin upgrade from the old `0.30` version used by `grunt-flowbin` to the `0.33` version which is installed by `web-ext` as a dev dependency but currently not unused by the `flowbin:check`).

The initial issue described, the missing flow binary, sounds like a issue with the result of the `npm install` command (and probably to the fact that `npm install` is currently non-deterministic and can give different results from run to run, from machine to machine... sigh :-( ), and probably the annoying "remove the `node_modules` dir entirely and recreate it by running `npm install` again" workaround can be able to fix the issue (unfortunately without giving us a clue about how it ended up that way in the first place).

While #583 is probably an invalid issue, because it has been created artificially by the workaround described above, which created an issue inside flow-bin modules itself (by basically turning it into a [fork bomb](https://en.wikipedia.org/wiki/Fork_bomb) ;-))

**Comment by onazaro** [comment] 2016-10-17 12:16
@rpl Thanks!
"Remove the `node_modules` dir entirely and recreate it by running `npm install` again" solved the problem for me.

**Comment by rpl** [comment] 2016-10-17 14:29
@onazaro I'm so glad to hear that it helped!

**Comment by rpl** [comment] 2016-10-17 14:34
Based on the issue analysis from the above comments (which has been confirmed by the reporter), this is an npm-related issue and not an issue in web-ext itself.

It has been solved by removing and recreating the "corrupted" `node_modules` dir.

**Closed by rpl** 2016-10-17 14:34 UTC
Labels: invalid
