### ISSUE TITLE
web-ext does not support browser_specific_settings when signing

### ISSUE THREAD

**Issue by Lusito** [mozilla/web-ext#1943] opened 2020-06-27 13:27 UTC
### Is this a feature request or a bug?
Bug

### What is the current behavior?

Update: It seems, that web-ext does not support `browser_specific_settings` and instead requires the old `applications` key to find the extension id.

### What is the expected or desired behavior?

web-ext should support the new key `browser_specific_settings` in addition to the old `applications` key to specify the extension-id

### Version information (for bug reports)

* **Firefox version**: 77.0.1
* **Your OS and version**: Win7
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
v12.16.3
6.14.4
4.3.0

**Comment by rpl** [comment] 2020-06-29 13:15
Closing as a duplicate of #1901.

In the meantime, you may be able to workaround the issue (without changing the manifest) by using the `--id` command line parameter.

(There is also a pull request, #1791 that did aim to fix the underlying issue, but it does requires some changes to make it ready to be merged, it may be good to refine that PR, by removing the formatting changes unrelated to the issue and finalize it to make it ready for one last review round and merge)

**Closed by rpl** 2020-06-29 13:15 UTC
Labels: state: duplicate
